In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [2]:
np.random.seed(1)

In [3]:
df = pd.read_csv("mental.csv")
df.head()

id  school_year  semester   age gender  height  weight  phq1  phq2  phq3  \
0  A1            1         1  19.0      m    1.50    75.0   2.0   1.0   1.0   
1  B2            1         1  18.0      m    1.68    56.0   2.0   0.0   1.0   
2  C3            1         1  19.0      m    1.74    76.0   1.0   1.0   0.0   
3  D4            1         1  18.0      f    1.68    67.0   2.0   2.0   3.0   
4  E5            1         1  18.0      m    1.80    83.0   0.0   1.0   1.0   

   ...  Unnamed: 245  Unnamed: 246  Unnamed: 247  Unnamed: 248  Unnamed: 249  \
0  ...           NaN           NaN           NaN           NaN           NaN   
1  ...           NaN           NaN           NaN           NaN           NaN   
2  ...           NaN           NaN           NaN           NaN           NaN   
3  ...           NaN           NaN           NaN           NaN           NaN   
4  ...           NaN           NaN           NaN           NaN           NaN   

   Unnamed: 250  Unnamed: 251  Unnamed: 252  Unnamed: 253  Unnamed: 254  
0           NaN           NaN           NaN           NaN           NaN  
1           NaN           NaN           NaN           NaN           NaN  
2           NaN           NaN           NaN           NaN           NaN  
3           NaN           NaN           NaN           NaN           NaN  
4           NaN           NaN           NaN           NaN           NaN  

[5 rows x 255 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 776 entries, 0 to 775
Columns: 255 entries, id to Unnamed: 254
dtypes: float64(246), int64(2), object(7)
memory usage: 1.5+ MB


## Data Cleaning

In [5]:
target = 'thoughts_of_dropping_out'

### Replace empty or errors by np.nan

In [6]:
# replace empty/erros by np.nan
df = df.replace(r'^\s+$', np.nan, regex=True)
df = df.replace('\t','',regex=True)
df = df.replace(' ','',regex=True)
df = df.replace('\?',np.nan,regex=True)
df = df.replace('\<',np.nan,regex=True)
df = df.replace('#NULL!',np.nan,regex=True)

#df

### Remove outliers

In [7]:
# Drop the column outliers as it is unrelated to the dependent variable
outliers = ['id','gender','bed_time','wake_up_time','reported_sleep_hours','nap_duration','weekly_study_hours']
df = df.drop(outliers,axis=1)
df.head()

school_year  semester   age  height  weight  phq1  phq2  phq3  phq4  phq5  \
0            1         1  19.0    1.50    75.0   2.0   1.0   1.0   1.0   2.0   
1            1         1  18.0    1.68    56.0   2.0   0.0   1.0   2.0   1.0   
2            1         1  19.0    1.74    76.0   1.0   1.0   0.0   3.0   1.0   
3            1         1  18.0    1.68    67.0   2.0   2.0   3.0   3.0   3.0   
4            1         1  18.0    1.80    83.0   0.0   1.0   1.0   2.0   1.0   

   ...  Unnamed: 245  Unnamed: 246  Unnamed: 247  Unnamed: 248  Unnamed: 249  \
0  ...           NaN           NaN           NaN           NaN           NaN   
1  ...           NaN           NaN           NaN           NaN           NaN   
2  ...           NaN           NaN           NaN           NaN           NaN   
3  ...           NaN           NaN           NaN           NaN           NaN   
4  ...           NaN           NaN           NaN           NaN           NaN   

   Unnamed: 250  Unnamed: 251  Unnamed: 252  Unnamed: 253  Unnamed: 254  
0           NaN           NaN           NaN           NaN           NaN  
1           NaN           NaN           NaN           NaN           NaN  
2           NaN           NaN           NaN           NaN           NaN  
3           NaN           NaN           NaN           NaN           NaN  
4           NaN           NaN           NaN           NaN           NaN  

[5 rows x 248 columns]

### Remove bad columns

In [8]:
def remove_bad_columns(df,bad_column_threshold):
    # find bad columns having too many missing values
    n_null = np.array(df.isnull().sum(axis=0))
    bad_col = np.array([]).astype(int)
    for i in range(len(n_null)):
        if n_null[i] >= bad_column_threshold:
            bad_col = np.append(bad_col,i)

    #print(bad_col)
    print('number of bad columns:',len(bad_col))

    # delete bad columns
    df = df.drop(df.columns[bad_col],axis=1)
    #df.info()
    return df  

In [9]:
df = remove_bad_columns(df,16)
df.info()

number of bad columns: 213
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 776 entries, 0 to 775
Data columns (total 35 columns):
school_year                      776 non-null int64
semester                         776 non-null int64
age                              775 non-null float64
height                           770 non-null float64
weight                           771 non-null float64
phq1                             774 non-null float64
phq2                             774 non-null float64
phq3                             774 non-null float64
phq4                             774 non-null float64
phq5                             771 non-null float64
phq6                             774 non-null float64
phq7                             774 non-null float64
phq8                             774 non-null float64
phq9                             774 non-null float64
thoughts_of_dropping_out         771 non-null float64
previous_depression_diagnosis    774 non-null float64
previous

### Remove bad rows

In [10]:
 # Find rows where target is missing
def find_missing_target_rows(df,target):
    # find rows where target is missing
    missing_row = df[target].isnull()
    print('Number of rows where target are missing:')
    print(sum(missing_row))

    #df = df[~missing_row]
    missing_row_indices = np.array([t for t in range(df.shape[0]) if missing_row[t]])
    
    return missing_row_indices

In [11]:
missing_target_rows = find_missing_target_rows(df,target)

Number of rows where target are missing:
5


We find bad rows which contain too many missing values, then remove them.

In [12]:
def find_bad_rows(df,bad_row_threshold):   
    # find bad rows having too many missing values
    n_null = np.array(df.isnull().sum(axis=1))
    bad_row = np.array([]).astype(int)
    for t in range(len(n_null)):
        if n_null[t] >= bad_row_threshold:
            bad_row = np.append(bad_row,t)

    #print(bad_row)
    print('number of bad rows:',len(bad_row))

    # delete bad rows
    #df = df.drop(bad_row)
    #df.info()
    return bad_row

In [13]:
bad_rows = find_bad_rows(df,6)
df.info()

number of bad rows: 9
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 776 entries, 0 to 775
Data columns (total 35 columns):
school_year                      776 non-null int64
semester                         776 non-null int64
age                              775 non-null float64
height                           770 non-null float64
weight                           771 non-null float64
phq1                             774 non-null float64
phq2                             774 non-null float64
phq3                             774 non-null float64
phq4                             774 non-null float64
phq5                             771 non-null float64
phq6                             774 non-null float64
phq7                             774 non-null float64
phq8                             774 non-null float64
phq9                             774 non-null float64
thoughts_of_dropping_out         771 non-null float64
previous_depression_diagnosis    774 non-null float64
previous_depr

In [14]:
del_rows = np.union1d(missing_target_rows,bad_rows)
print('number of rows need to delete:',len(del_rows))

df = df.drop(del_rows)

number of rows need to delete: 13


### Separate target and attributes

In [15]:
dfx = df.drop(target,axis=1)
dfy = df[target]

### Find variable type

In [16]:
# number of uniques of each column (excluding NaN)
nu = np.array([len(pd.unique(dfx[col].dropna())) for col in dfx.columns])
print('number of uniques of each variable:')
print(nu)

number of uniques of each variable:
[ 4  7 15 47 88  4  4  4  4  4  4  4  4  4  2  2  4  4  4  4  4  4  4  2
  2  5  5  5  5  5  5  5  5  5]


In [17]:
def define_variable_type(df,nu):
    i_binary = [] ; i_category = [] ; i_continuous = []
    for i in range(len(nu)):
        if nu[i] == 2: # binary 
            i_binary.append(i)
        elif nu[i] < 5: # !!!! NOTE: this is not always correct, depending on data
            i_category.append(i)
        else:
            i_continuous.append(i)

    print('i_binary:',i_binary)
    print('i_category:',i_category)   
    #i_binary, i_category, i_continuous
    
    variable_type  = np.ones(len(nu))  # binary
    variable_type[i_category] = 2   # categorical
    variable_type[i_continuous] = 3 # continuous

    return variable_type #,i_binary,i_category,i_continuous

In [18]:
variable_type = define_variable_type(dfx,nu)
print('variable type:',variable_type)

i_binary: [14, 15, 23, 24]
i_category: [0, 5, 6, 7, 8, 9, 10, 11, 12, 13, 16, 17, 18, 19, 20, 21, 22]
variable type: [2. 3. 3. 3. 3. 2. 2. 2. 2. 2. 2. 2. 2. 2. 1. 1. 2. 2. 2. 2. 2. 2. 2. 1.
 1. 3. 3. 3. 3. 3. 3. 3. 3. 3.]


### Impute missing values of attributes

In [19]:
def impute_missing(df,variable_type):
    # impute binary and categorical variables by the most frequency (in each column)
    # continuous variable by median
    # input: df: pandas data frame, variable_type: list
    # output: df2: pandas data frame
    df2 = df.copy()
    for i,col in enumerate(df.columns):
        if variable_type[i] < 3: # binary or caterogy
            df2[col] = df[col].fillna(df[col].mode().iloc[0])
        else: # continuous
            df2[col] = df[col].fillna(df[col].median())    
    return df2       

In [20]:
dfx_imputed = impute_missing(dfx,variable_type)
dfx_imputed.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 763 entries, 0 to 775
Data columns (total 34 columns):
school_year                      763 non-null int64
semester                         763 non-null int64
age                              763 non-null float64
height                           763 non-null float64
weight                           763 non-null float64
phq1                             763 non-null float64
phq2                             763 non-null float64
phq3                             763 non-null float64
phq4                             763 non-null float64
phq5                             763 non-null float64
phq6                             763 non-null float64
phq7                             763 non-null float64
phq8                             763 non-null float64
phq9                             763 non-null float64
previous_depression_diagnosis    763 non-null float64
previous_depression_treatment    763 non-null float64
gad1                             76

## Data Processing

### Attributes

In [21]:
def convert_binary_and_category(x,variable_type):
    """
    convert binary to +-1, category to one hot; remain continuous.
    """    
    onehot_encoder = OneHotEncoder(sparse=False,categories='auto')

    # create 2 initial columns
    x_new = np.zeros((x.shape[0],2))

    for i,i_type in enumerate(variable_type):
        if i_type == 1: # binary
            unique_value = np.unique(x[:,i])
            x1 = np.array([-1. if value == unique_value[0] else 1. for value in x[:,i]])        
            x_new = np.hstack((x_new,x1[:,np.newaxis]))

        elif i_type == 2: # category
            x1 = onehot_encoder.fit_transform(x[:,i].reshape(-1,1))
            x_new = np.hstack((x_new,x1))
            
        else: # continuous      
            x_new = np.hstack((x_new,x[:,i][:,np.newaxis]))      

    # drop the 2 initial column
    x_new = x_new[:,2:]
    
    return x_new.astype(float)

In [22]:
# convert x
x = np.array(dfx_imputed)
x_new = convert_binary_and_category(x,variable_type)

print(x_new.shape)
print(x_new)

(763, 85)
[[1. 0. 0. ... 1. 1. 1.]
 [1. 0. 0. ... 2. 2. 2.]
 [1. 0. 0. ... 1. 1. 1.]
 ...
 [0. 0. 0. ... 1. 0. 1.]
 [0. 0. 0. ... 1. 3. 4.]
 [0. 0. 0. ... 0. 0. 4.]]


### Target

In [23]:
y = np.array(dfy)
#print(np.unique(y,return_counts=True))

# convert taget to 0 and 1
y_new = y
#y_new = np.ones(y.shape[0])
#y_new[y =='No'] = 0

print(np.unique(y_new,return_counts=True))

(array([0., 1.]), array([616, 147]))


In [24]:
# combine X and y and save to a file
xy_new = np.hstack((x_new,y_new[:,np.newaxis]))
np.savetxt('data_processed.dat',xy_new,fmt='%f')