In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
#from sklearn.preprocessing import Imputer

In [2]:
np.random.seed(1)

In [3]:
df = pd.read_csv("coag.csv")
df

NO  Y  Sex\n1.Male\n2.Female   Age  Before\ntreatment  \
0        1  1                      1  72.0                  1   
1        2  1                      2  76.0                  1   
2        3  2                      1  93.0                  2   
3        4  1                      2  76.0                  2   
4        5  1                      1  76.0                  2   
5        6  2                      1  69.0                  2   
6        7  2                      2  63.0                  1   
7        8  2                      1  84.0                  2   
8        9  1                      1  69.0                  1   
9       10  2                      1  63.0                  1   
10      11  1                      1  67.0                  1   
11      12  1                      2  73.0                  2   
12      13  1                      2  71.0                  2   
13      14  1                      2  68.0                  2   
14      15  1                      2  61.0                  1   
15      16  2                      2  84.0                  2   
16      17  1                      1  73.0                  2   
17      18  1                      1  64.0                  1   
18      19  2                      1  34.0                  1   
19      20  1                      1  72.0                  1   
20      21  1                      2  83.0                  2   
21      22  1                      2  77.0                  2   
22      23  1                      2  63.0                  2   
23      24  2                      1  36.0                  1   
24      25  1                      1  70.0                  2   
25      26  1                      1  78.0                  2   
26      27  2                      1  68.0                  2   
27      28  2                      2  87.0                  2   
28      29  1                      1  66.0                  1   
29      30  1                      2  19.0                  1   
...    ... ..                    ...   ...                ...   
1468  1469  1                      1  83.0                  2   
1469  1470  1                      1  87.0                  2   
1470  1471  2                      2  88.0                  2   
1471  1472  1                      1  69.0                  2   
1472  1473  2                      2  65.0                  1   
1473  1474  2                      1  69.0                  2   
1474  1475  2                      2  73.0                  1   
1475  1476  1                      1  93.0                  2   
1476  1477  2                      1  81.0                  2   
1477  1478  1                      1  47.0                  2   
1478  1479  1                      1  75.0                  2   
1479  1480  1                      2  89.0                  2   
1480  1481  2                      1  86.0                  2   
1481  1482  1                      2  83.0                  2   
1482  1483  2                      1  67.0                  2   
1483  1484  1                      1   NaN                  1   
1484  1485  2                      1  76.0                  2   
1485  1486  1                      2  76.0                  1   
1486  1487  1                      2  42.0                  1   
1487  1488  1                      2  65.0                  2   
1488  1489  2                      1  88.0                  2   
1489  1490  2                      2  74.0                  1   
1490  1491  1                      1   6.0                  2   
1491  1492  1                      1  60.0                  2   
1492  1493  1                      2  58.0                  2   
1493  1494  2                      1  84.0                  2   
1494  1495  1                      1   4.0                  2   
1495  1496  1                      1  65.0                  1   
1496  1497  2                      1  80.0                  1   
1497  1498  2                      1  82.0 

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1498 entries, 0 to 1497
Data columns (total 29 columns):
NO                                        1498 non-null int64
Y                                         1498 non-null int64
Sex
1.Male
2.Female                       1498 non-null int64
Age                                       1494 non-null float64
Before
treatment                          1498 non-null int64
Severity
1.mild/moderate
2.severe         1498 non-null int64
PT                                        1498 non-null object
Platelet                                  1498 non-null float64
FDP                                       1303 non-null float64
SIRS_t1                                   1498 non-null int64
SIRS
3 or more
1. positive
2. negative    1498 non-null int64
JAAM DIC
score                            1498 non-null int64
JAAM
DIC
1.positive
2.negative            1498 non-null int64
SOFA
respiratory                          1498 non-null int64
SOFA
respiratory
0

In [5]:
# replace empty by nan
df = df.replace(r'^\s+$', np.nan, regex=True)
df

NO  Y  Sex\n1.Male\n2.Female   Age  Before\ntreatment  \
0        1  1                      1  72.0                  1   
1        2  1                      2  76.0                  1   
2        3  2                      1  93.0                  2   
3        4  1                      2  76.0                  2   
4        5  1                      1  76.0                  2   
5        6  2                      1  69.0                  2   
6        7  2                      2  63.0                  1   
7        8  2                      1  84.0                  2   
8        9  1                      1  69.0                  1   
9       10  2                      1  63.0                  1   
10      11  1                      1  67.0                  1   
11      12  1                      2  73.0                  2   
12      13  1                      2  71.0                  2   
13      14  1                      2  68.0                  2   
14      15  1                      2  61.0                  1   
15      16  2                      2  84.0                  2   
16      17  1                      1  73.0                  2   
17      18  1                      1  64.0                  1   
18      19  2                      1  34.0                  1   
19      20  1                      1  72.0                  1   
20      21  1                      2  83.0                  2   
21      22  1                      2  77.0                  2   
22      23  1                      2  63.0                  2   
23      24  2                      1  36.0                  1   
24      25  1                      1  70.0                  2   
25      26  1                      1  78.0                  2   
26      27  2                      1  68.0                  2   
27      28  2                      2  87.0                  2   
28      29  1                      1  66.0                  1   
29      30  1                      2  19.0                  1   
...    ... ..                    ...   ...                ...   
1468  1469  1                      1  83.0                  2   
1469  1470  1                      1  87.0                  2   
1470  1471  2                      2  88.0                  2   
1471  1472  1                      1  69.0                  2   
1472  1473  2                      2  65.0                  1   
1473  1474  2                      1  69.0                  2   
1474  1475  2                      2  73.0                  1   
1475  1476  1                      1  93.0                  2   
1476  1477  2                      1  81.0                  2   
1477  1478  1                      1  47.0                  2   
1478  1479  1                      1  75.0                  2   
1479  1480  1                      2  89.0                  2   
1480  1481  2                      1  86.0                  2   
1481  1482  1                      2  83.0                  2   
1482  1483  2                      1  67.0                  2   
1483  1484  1                      1   NaN                  1   
1484  1485  2                      1  76.0                  2   
1485  1486  1                      2  76.0                  1   
1486  1487  1                      2  42.0                  1   
1487  1488  1                      2  65.0                  2   
1488  1489  2                      1  88.0                  2   
1489  1490  2                      2  74.0                  1   
1490  1491  1                      1   6.0                  2   
1491  1492  1                      1  60.0                  2   
1492  1493  1                      2  58.0                  2   
1493  1494  2                      1  84.0                  2   
1494  1495  1                      1   4.0                  2   
1495  1496  1                      1  65.0                  1   
1496  1497  2                      1  80.0                  1   
1497  1498  2                      1  82.0 

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1498 entries, 0 to 1497
Data columns (total 29 columns):
NO                                        1498 non-null int64
Y                                         1498 non-null int64
Sex
1.Male
2.Female                       1498 non-null int64
Age                                       1494 non-null float64
Before
treatment                          1498 non-null int64
Severity
1.mild/moderate
2.severe         1498 non-null int64
PT                                        1498 non-null object
Platelet                                  1498 non-null float64
FDP                                       1303 non-null float64
SIRS_t1                                   1498 non-null int64
SIRS
3 or more
1. positive
2. negative    1498 non-null int64
JAAM DIC
score                            1498 non-null int64
JAAM
DIC
1.positive
2.negative            1498 non-null int64
SOFA
respiratory                          1498 non-null int64
SOFA
respiratory
0

In [7]:
df = df.replace('\t','',regex=True)
df = df.replace(' ','',regex=True)
df = df.replace('\?','np.nan',regex=True)

## Data Cleaning

In [8]:
# Drop the column `ID` as it is unrelated to the dependent variable
df = df.drop(['NO','PT'],axis=1)
df

Y  Sex\n1.Male\n2.Female   Age  Before\ntreatment  \
0     1                      1  72.0                  1   
1     1                      2  76.0                  1   
2     2                      1  93.0                  2   
3     1                      2  76.0                  2   
4     1                      1  76.0                  2   
5     2                      1  69.0                  2   
6     2                      2  63.0                  1   
7     2                      1  84.0                  2   
8     1                      1  69.0                  1   
9     2                      1  63.0                  1   
10    1                      1  67.0                  1   
11    1                      2  73.0                  2   
12    1                      2  71.0                  2   
13    1                      2  68.0                  2   
14    1                      2  61.0                  1   
15    2                      2  84.0                  2   
16    1                      1  73.0                  2   
17    1                      1  64.0                  1   
18    2                      1  34.0                  1   
19    1                      1  72.0                  1   
20    1                      2  83.0                  2   
21    1                      2  77.0                  2   
22    1                      2  63.0                  2   
23    2                      1  36.0                  1   
24    1                      1  70.0                  2   
25    1                      1  78.0                  2   
26    2                      1  68.0                  2   
27    2                      2  87.0                  2   
28    1                      1  66.0                  1   
29    1                      2  19.0                  1   
...  ..                    ...   ...                ...   
1468  1                      1  83.0                  2   
1469  1                      1  87.0                  2   
1470  2                      2  88.0                  2   
1471  1                      1  69.0                  2   
1472  2                      2  65.0                  1   
1473  2                      1  69.0                  2   
1474  2                      2  73.0                  1   
1475  1                      1  93.0                  2   
1476  2                      1  81.0                  2   
1477  1                      1  47.0                  2   
1478  1                      1  75.0                  2   
1479  1                      2  89.0                  2   
1480  2                      1  86.0                  2   
1481  1                      2  83.0                  2   
1482  2                      1  67.0                  2   
1483  1                      1   NaN                  1   
1484  2                      1  76.0                  2   
1485  1                      2  76.0                  1   
1486  1                      2  42.0                  1   
1487  1                      2  65.0                  2   
1488  2                      1  88.0                  2   
1489  2                      2  74.0                  1   
1490  1                      1   6.0                  2   
1491  1                      1  60.0                  2   
1492  1                      2  58.0                  2   
1493  2                      1  84.0                  2   
1494  1                      1   4.0                  2   
1495  1                      1  65.0                  1   
1496  2                      1  80.0                  1   
1497  2                      1  82.0                  1   

      Severity\n1.mild/moderate\n2.severe  Platelet     FDP  SIRS_t1  \
0                                       2      41.0   17.00        2   
1                                       2      23.0   18.70        3   
2                                       2      57.0   22.90        3   
3                                       2      66.0   23.40

In [9]:
# Remove rows where taget are missing
missing_row = df['Y'].isnull()
print('Number of rows where target are missing:')
print(sum(missing_row))

df = df[~missing_row]
df

Number of rows where target are missing:
0


Y  Sex\n1.Male\n2.Female   Age  Before\ntreatment  \
0     1                      1  72.0                  1   
1     1                      2  76.0                  1   
2     2                      1  93.0                  2   
3     1                      2  76.0                  2   
4     1                      1  76.0                  2   
5     2                      1  69.0                  2   
6     2                      2  63.0                  1   
7     2                      1  84.0                  2   
8     1                      1  69.0                  1   
9     2                      1  63.0                  1   
10    1                      1  67.0                  1   
11    1                      2  73.0                  2   
12    1                      2  71.0                  2   
13    1                      2  68.0                  2   
14    1                      2  61.0                  1   
15    2                      2  84.0                  2   
16    1                      1  73.0                  2   
17    1                      1  64.0                  1   
18    2                      1  34.0                  1   
19    1                      1  72.0                  1   
20    1                      2  83.0                  2   
21    1                      2  77.0                  2   
22    1                      2  63.0                  2   
23    2                      1  36.0                  1   
24    1                      1  70.0                  2   
25    1                      1  78.0                  2   
26    2                      1  68.0                  2   
27    2                      2  87.0                  2   
28    1                      1  66.0                  1   
29    1                      2  19.0                  1   
...  ..                    ...   ...                ...   
1468  1                      1  83.0                  2   
1469  1                      1  87.0                  2   
1470  2                      2  88.0                  2   
1471  1                      1  69.0                  2   
1472  2                      2  65.0                  1   
1473  2                      1  69.0                  2   
1474  2                      2  73.0                  1   
1475  1                      1  93.0                  2   
1476  2                      1  81.0                  2   
1477  1                      1  47.0                  2   
1478  1                      1  75.0                  2   
1479  1                      2  89.0                  2   
1480  2                      1  86.0                  2   
1481  1                      2  83.0                  2   
1482  2                      1  67.0                  2   
1483  1                      1   NaN                  1   
1484  2                      1  76.0                  2   
1485  1                      2  76.0                  1   
1486  1                      2  42.0                  1   
1487  1                      2  65.0                  2   
1488  2                      1  88.0                  2   
1489  2                      2  74.0                  1   
1490  1                      1   6.0                  2   
1491  1                      1  60.0                  2   
1492  1                      2  58.0                  2   
1493  2                      1  84.0                  2   
1494  1                      1   4.0                  2   
1495  1                      1  65.0                  1   
1496  2                      1  80.0                  1   
1497  2                      1  82.0                  1   

      Severity\n1.mild/moderate\n2.severe  Platelet     FDP  SIRS_t1  \
0                                       2      41.0   17.00        2   
1                                       2      23.0   18.70        3   
2                                       2      57.0   22.90        3   
3                                       2      66.0   23.40

We determine and drop the variables with excessive missing values from the dataset.

In [10]:
def remove_bad_columns(df,bad_column_threshold):
    # find bad columns having too many missing values
    n_null = np.array(df.isnull().sum(axis=0))
    bad_col = np.array([]).astype(int)
    for i in range(len(n_null)):
        if n_null[i] >= bad_column_threshold:
            bad_col = np.append(bad_col,i)

    #print(bad_col)
    print('number of bad columns:',len(bad_col))

    # delete bad columns
    df = df.drop(df.columns[bad_col],axis=1)
    #df.info()
    return df   

In [11]:
df = remove_bad_columns(df,200)
df.info()

number of bad columns: 7
<class 'pandas.core.frame.DataFrame'>
Int64Index: 1498 entries, 0 to 1497
Data columns (total 20 columns):
Y                                         1498 non-null int64
Sex
1.Male
2.Female                       1498 non-null int64
Age                                       1494 non-null float64
Before
treatment                          1498 non-null int64
Severity
1.mild/moderate
2.severe         1498 non-null int64
Platelet                                  1498 non-null float64
FDP                                       1303 non-null float64
SIRS_t1                                   1498 non-null int64
SIRS
3 or more
1. positive
2. negative    1498 non-null int64
JAAM DIC
score                            1498 non-null int64
JAAM
DIC
1.positive
2.negative            1498 non-null int64
SOFA
respiratory                          1498 non-null int64
SOFA
coagulation                          1498 non-null int64
SOFA
hepatic                              1498 non-null 

We find bad rows which contain too many missing values, then remove them.

In [12]:
def remove_bad_rows(df,bad_row_threshold):   
    # find bad rows having too many missing values
    n_null = np.array(df.isnull().sum(axis=1))
    bad_row = np.array([]).astype(int)
    for t in range(len(n_null)):
        if n_null[t] >= bad_row_threshold:
            bad_row = np.append(bad_row,t)

    #print(bad_row)
    print('number of bad rows:',len(bad_row))

    # delete bad rows
    df = df.drop(bad_row)
    #df.info()
    return df

In [13]:
df = remove_bad_rows(df,5)
df.info()

number of bad rows: 0
<class 'pandas.core.frame.DataFrame'>
Int64Index: 1498 entries, 0 to 1497
Data columns (total 20 columns):
Y                                         1498 non-null int64
Sex
1.Male
2.Female                       1498 non-null int64
Age                                       1494 non-null float64
Before
treatment                          1498 non-null int64
Severity
1.mild/moderate
2.severe         1498 non-null int64
Platelet                                  1498 non-null float64
FDP                                       1303 non-null float64
SIRS_t1                                   1498 non-null int64
SIRS
3 or more
1. positive
2. negative    1498 non-null int64
JAAM DIC
score                            1498 non-null int64
JAAM
DIC
1.positive
2.negative            1498 non-null int64
SOFA
respiratory                          1498 non-null int64
SOFA
coagulation                          1498 non-null int64
SOFA
hepatic                              1498 non-null int

For convenience, we separate independents `X` and dependent `y` from the data.

In [14]:
dfx = df.drop('Y',axis=1)
dfy = df['Y']

In [15]:
# number of uniques of each column (excluding NaN)
nu = np.array([len(pd.unique(dfx[col].dropna())) for col in dfx.columns])
print('number of uniques of each variable:')
print(nu)

number of uniques of each variable:
[  2  97   2   2 236 688   5   2   9   2   5   5   5   5   5   9   5   7
   2]


In [16]:
def define_variable_type(df,nu):
    i_binary = [] ; i_category = [] ; i_continuous = []
    for i in range(len(nu)):
        if nu[i] == 2: # binary 
            i_binary.append(i)
        elif nu[i] < 5: # !!!! NOTE: this is not always correct, depending on data
            i_category.append(i)
        else:
            i_continuous.append(i)

    print('i_binary:',i_binary)
    print('i_category:',i_category)   
    #i_binary, i_category, i_continuous
    
    variable_type  = np.ones(len(nu))  # binary
    variable_type[i_category] = 2   # categorical
    variable_type[i_continuous] = 3 # continuous

    return variable_type #,i_binary,i_category,i_continuous

In [17]:
variable_type = define_variable_type(dfx,nu)
print('variable type:',variable_type)

i_binary: [0, 2, 3, 7, 9, 18]
i_category: []
variable type: [1. 3. 1. 1. 3. 3. 3. 1. 3. 1. 3. 3. 3. 3. 3. 3. 3. 3. 1.]


In [18]:
def impute_missing(df,variable_type):
    # impute binary and categorical variables by the most frequency (in each column)
    # continuous variable by median
    # input: df: pandas data frame, variable_type: list
    # output: df2: pandas data frame
    df2 = df.copy()
    for i,col in enumerate(df.columns):
        if variable_type[i] < 3: # binary or caterogy
            df2[col] = df[col].fillna(df[col].mode().iloc[0])
        else: # continuous
            df2[col] = df[col].fillna(df[col].median())    
    return df2       

In [19]:
dfx_imputed = impute_missing(dfx,variable_type)
dfx_imputed

Sex\n1.Male\n2.Female   Age  Before\ntreatment  \
0                         1  72.0                  1   
1                         2  76.0                  1   
2                         1  93.0                  2   
3                         2  76.0                  2   
4                         1  76.0                  2   
5                         1  69.0                  2   
6                         2  63.0                  1   
7                         1  84.0                  2   
8                         1  69.0                  1   
9                         1  63.0                  1   
10                        1  67.0                  1   
11                        2  73.0                  2   
12                        2  71.0                  2   
13                        2  68.0                  2   
14                        2  61.0                  1   
15                        2  84.0                  2   
16                        1  73.0                  2   
17                        1  64.0                  1   
18                        1  34.0                  1   
19                        1  72.0                  1   
20                        2  83.0                  2   
21                        2  77.0                  2   
22                        2  63.0                  2   
23                        1  36.0                  1   
24                        1  70.0                  2   
25                        1  78.0                  2   
26                        1  68.0                  2   
27                        2  87.0                  2   
28                        1  66.0                  1   
29                        2  19.0                  1   
...                     ...   ...                ...   
1468                      1  83.0                  2   
1469                      1  87.0                  2   
1470                      2  88.0                  2   
1471                      1  69.0                  2   
1472                      2  65.0                  1   
1473                      1  69.0                  2   
1474                      2  73.0                  1   
1475                      1  93.0                  2   
1476                      1  81.0                  2   
1477                      1  47.0                  2   
1478                      1  75.0                  2   
1479                      2  89.0                  2   
1480                      1  86.0                  2   
1481                      2  83.0                  2   
1482                      1  67.0                  2   
1483                      1  71.0                  1   
1484                      1  76.0                  2   
1485                      2  76.0                  1   
1486                      2  42.0                  1   
1487                      2  65.0                  2   
1488                      1  88.0                  2   
1489                      2  74.0                  1   
1490                      1   6.0                  2   
1491                      1  60.0                  2   
1492                      2  58.0                  2   
1493                      1  84.0                  2   
1494                      1   4.0                  2   
1495                      1  65.0                  1   
1496                      1  80.0                  1   
1497                      1  82.0                  1   

      Severity\n1.mild/moderate\n2.severe  Platelet     FDP  SIRS_t1  \
0                                       2      41.0   17.00        2   
1                                       2      23.0   18.70        3   
2                                       2      57.0   22.90        3   
3                                       2      66.0   23.40        2   
4                                       2      44.0    3.90        4   
5                                       2      13.0    5.30        3   
6                            

In [20]:
dfx_imputed.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1498 entries, 0 to 1497
Data columns (total 19 columns):
Sex
1.Male
2.Female                       1498 non-null int64
Age                                       1498 non-null float64
Before
treatment                          1498 non-null int64
Severity
1.mild/moderate
2.severe         1498 non-null int64
Platelet                                  1498 non-null float64
FDP                                       1498 non-null float64
SIRS_t1                                   1498 non-null int64
SIRS
3 or more
1. positive
2. negative    1498 non-null int64
JAAM DIC
score                            1498 non-null int64
JAAM
DIC
1.positive
2.negative            1498 non-null int64
SOFA
respiratory                          1498 non-null int64
SOFA
coagulation                          1498 non-null int64
SOFA
hepatic                              1498 non-null int64
SOFA
cardiovascular                       1498 non-null int64
SOFA
renal         

## Data Processing

### Attributes

In [21]:
def convert_binary_and_category(x,variable_type):
    """
    convert binary to +-1, category to one hot; remain continuous.
    """
    
    onehot_encoder = OneHotEncoder(sparse=False,categories='auto')

    # create 2 initial columns
    x_new = np.zeros((x.shape[0],2))

    for i,i_type in enumerate(variable_type):
        if i_type == 1: # binary
            unique_value = np.unique(x[:,i])
            x1 = np.array([-1. if value == unique_value[0] else 1. for value in x[:,i]])        
            x_new = np.hstack((x_new,x1[:,np.newaxis]))

        elif i_type == 2: # category
            x1 = onehot_encoder.fit_transform(x[:,i].reshape(-1,1))
            x_new = np.hstack((x_new,x1))
            
        else: # continuous      
            x_new = np.hstack((x_new,x[:,i][:,np.newaxis]))      

    # drop the 2 initial column
    x_new = x_new[:,2:]
    
    return x_new.astype(float)

In [22]:
# convert x
x = np.array(dfx_imputed)
x_new = convert_binary_and_category(x,variable_type)

print(x_new.shape)
print(x_new)

(1498, 19)
[[-1. 72. -1. ...  2.  4.  1.]
 [ 1. 76. -1. ...  4.  6. -1.]
 [-1. 93.  1. ...  4.  6. -1.]
 ...
 [-1. 65. -1. ...  2.  4.  1.]
 [-1. 80. -1. ...  4.  6. -1.]
 [-1. 82. -1. ...  4.  6. -1.]]


### Target

In [23]:
y = np.array(dfy)
print(np.unique(y,return_counts=True))

# convert target to 0 and 1
y_new = np.ones(y.shape[0])
y_new[y ==2] = 0

# if target is already 0 and 1
#y_new = y #and delete lines below convert  
print(np.unique(y_new,return_counts=True))

(array([1, 2]), array([994, 504]))
(array([0., 1.]), array([504, 994]))


In [24]:
# combine X and y and save to a file
xy_new = np.hstack((x_new,y_new[:,np.newaxis]))
np.savetxt('coag_processed.dat',xy_new,fmt='%f')