In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
#from sklearn.preprocessing import Imputer

In [2]:
np.random.seed(1)

In [3]:
df = pd.read_csv("ef.csv")
df

sex  m32  m33_1   PE  m33_2  m34  m35  m35_1_2  m35_2_2  m35_1_3  ...  \
0       1    1    1.0  1.0    1.0    1    2      1.0     11.0    999.0  ...   
1       1  999    NaN  NaN    NaN    5    1      NaN      NaN      NaN  ...   
2       1    2    1.0  1.0    1.0    1    1      NaN      NaN      NaN  ...   
3       1    5    2.0  2.0    3.0    2    1      NaN      NaN      NaN  ...   
4       1   60    2.0  2.0   45.0    5    1      NaN      NaN      NaN  ...   
5       1   60    2.0  2.0   10.0    5    1      NaN      NaN      NaN  ...   
6       1    5    2.0  2.0    2.0    3    1      NaN      NaN      NaN  ...   
7       1   10    2.0  2.0    5.0    4    1      NaN      NaN      NaN  ...   
8       1  999  999.0  NaN    NaN  999    1      NaN      NaN      NaN  ...   
9       1   30    2.0  2.0  999.0    5    1      NaN      NaN      NaN  ...   
10      1    6    2.0  2.0    5.0    4    2    999.0      NaN    999.0  ...   
11      1    5    2.0  2.0    5.0    4    1      NaN      NaN      NaN  ...   
12      1   10    2.0  2.0   10.0    5    1      NaN      NaN      NaN  ...   
13      1    3    1.0  1.0    1.0    3    1      NaN      NaN      NaN  ...   
14      1    5    2.0  2.0    5.0    4    1      NaN      NaN      NaN  ...   
15      1   10    2.0  2.0    8.0    3    1      NaN      NaN      NaN  ...   
16      1   15    2.0  2.0   10.0    4    1      NaN      NaN      NaN  ...   
17      1   15    2.0  2.0    8.0    4    1      NaN      NaN      NaN  ...   
18      1  999    NaN  NaN    NaN    3    1      NaN      NaN      NaN  ...   
19      1    2    2.0  2.0    2.0    5    1      NaN      NaN      NaN  ...   
20      1  999    1.0  1.0    1.0    5    1      NaN      NaN      NaN  ...   
21      1   30    2.0  2.0   10.0    4    1      NaN      NaN      NaN  ...   
22      1    5    2.0  2.0    3.0    5    1      NaN      NaN      NaN  ...   
23      1   10    2.0  2.0   10.0    5    1      NaN      NaN      NaN  ...   
24      1    3    2.0  2.0    2.0    5    1      NaN      NaN      NaN  ...   
25      1  999    NaN  NaN    NaN  999    1      NaN      NaN      NaN  ...   
26      1   15    2.0  2.0    2.0    5    1      NaN      NaN      NaN  ...   
27      1    5    2.0  2.0    5.0    5    1      NaN      NaN      NaN  ...   
28      1   10    2.0  2.0    8.0    5    1      NaN      NaN      NaN  ...   
29      1   20    2.0  2.0   20.0    5    1      NaN      NaN      NaN  ...   
...   ...  ...    ...  ...    ...  ...  ...      ...      ...      ...  ...   
974     1  999  999.0  NaN    NaN    5    1      NaN      NaN      NaN  ...   
975     1    8    2.0  2.0    5.0    5    1      NaN      NaN      NaN  ...   
976     1   10    2.0  2.0    8.0    6    1      NaN      NaN      NaN  ...   
977     1   10    2.0  2.0    5.0    5    1      NaN      NaN      NaN  ...   
978     1    5    2.0  2.0    5.0    4    1      NaN      NaN      NaN  ...   
979     1   15    2.0  2.0    6.0    4    1      NaN      NaN      NaN  ...   
980     1   15    2.0  2.0   15.0    5    1      NaN      NaN      NaN  ...   
981     1    0    1.0  1.0    1.0    5    1      NaN      NaN      NaN  ...   
982     1   15    2.0  2.0   10.0    5    1      NaN      NaN      NaN  ...   
983     1   15    2.0  2.0   10.0    5    1      NaN      NaN      NaN  ...   
984     1   50    2.0  2.0   30.0    4    1      NaN      NaN      NaN  ...   
985     1   30    2.0  2.0   15.0    4    1      NaN      NaN      NaN  ...   
986     1   45    2.0  2.0   20.0    4    1      NaN      NaN      NaN  ...   
987     1   40    2.0  2.0   15.0    5    1      NaN      NaN      NaN  ...   
988     1   10    2.0  2.0    5.0    3    1      NaN      NaN      NaN  ...   
989     1   30    2.0  2.0   10.0    3    1      NaN      NaN      NaN  ...   
990     1   40    2.0  2.0   15.0    4    1      NaN      NaN      NaN  ...   
991     1   30    2.0  2.0   15.0    4    1      NaN      NaN      NaN  ...   
992     1   40    2.0  2.0   20.0    3    1      NaN    

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1004 entries, 0 to 1003
Data columns (total 55 columns):
sex                    1004 non-null int64
m32                    1004 non-null int64
m33_1                  920 non-null float64
PE                     816 non-null float64
m33_2                  816 non-null float64
m34                    1004 non-null int64
m35                    1004 non-null int64
m35_1_2                126 non-null float64
m35_2_2                43 non-null float64
m35_1_3                126 non-null float64
m35_2_3                46 non-null float64
m36_3                  133 non-null float64
m36_4                  133 non-null float64
m42                    1004 non-null int64
m43                    1004 non-null int64
m44                    1004 non-null int64
m45                    1004 non-null int64
m46                    1004 non-null int64
m47                    1004 non-null int64
m48                    1004 non-null int64
m49                    100

In [5]:
# replace empty by nan
df = df.replace(r'^\s+$', np.nan, regex=True)
df

sex  m32  m33_1   PE  m33_2  m34  m35  m35_1_2  m35_2_2  m35_1_3  ...  \
0       1    1    1.0  1.0    1.0    1    2      1.0     11.0    999.0  ...   
1       1  999    NaN  NaN    NaN    5    1      NaN      NaN      NaN  ...   
2       1    2    1.0  1.0    1.0    1    1      NaN      NaN      NaN  ...   
3       1    5    2.0  2.0    3.0    2    1      NaN      NaN      NaN  ...   
4       1   60    2.0  2.0   45.0    5    1      NaN      NaN      NaN  ...   
5       1   60    2.0  2.0   10.0    5    1      NaN      NaN      NaN  ...   
6       1    5    2.0  2.0    2.0    3    1      NaN      NaN      NaN  ...   
7       1   10    2.0  2.0    5.0    4    1      NaN      NaN      NaN  ...   
8       1  999  999.0  NaN    NaN  999    1      NaN      NaN      NaN  ...   
9       1   30    2.0  2.0  999.0    5    1      NaN      NaN      NaN  ...   
10      1    6    2.0  2.0    5.0    4    2    999.0      NaN    999.0  ...   
11      1    5    2.0  2.0    5.0    4    1      NaN      NaN      NaN  ...   
12      1   10    2.0  2.0   10.0    5    1      NaN      NaN      NaN  ...   
13      1    3    1.0  1.0    1.0    3    1      NaN      NaN      NaN  ...   
14      1    5    2.0  2.0    5.0    4    1      NaN      NaN      NaN  ...   
15      1   10    2.0  2.0    8.0    3    1      NaN      NaN      NaN  ...   
16      1   15    2.0  2.0   10.0    4    1      NaN      NaN      NaN  ...   
17      1   15    2.0  2.0    8.0    4    1      NaN      NaN      NaN  ...   
18      1  999    NaN  NaN    NaN    3    1      NaN      NaN      NaN  ...   
19      1    2    2.0  2.0    2.0    5    1      NaN      NaN      NaN  ...   
20      1  999    1.0  1.0    1.0    5    1      NaN      NaN      NaN  ...   
21      1   30    2.0  2.0   10.0    4    1      NaN      NaN      NaN  ...   
22      1    5    2.0  2.0    3.0    5    1      NaN      NaN      NaN  ...   
23      1   10    2.0  2.0   10.0    5    1      NaN      NaN      NaN  ...   
24      1    3    2.0  2.0    2.0    5    1      NaN      NaN      NaN  ...   
25      1  999    NaN  NaN    NaN  999    1      NaN      NaN      NaN  ...   
26      1   15    2.0  2.0    2.0    5    1      NaN      NaN      NaN  ...   
27      1    5    2.0  2.0    5.0    5    1      NaN      NaN      NaN  ...   
28      1   10    2.0  2.0    8.0    5    1      NaN      NaN      NaN  ...   
29      1   20    2.0  2.0   20.0    5    1      NaN      NaN      NaN  ...   
...   ...  ...    ...  ...    ...  ...  ...      ...      ...      ...  ...   
974     1  999  999.0  NaN    NaN    5    1      NaN      NaN      NaN  ...   
975     1    8    2.0  2.0    5.0    5    1      NaN      NaN      NaN  ...   
976     1   10    2.0  2.0    8.0    6    1      NaN      NaN      NaN  ...   
977     1   10    2.0  2.0    5.0    5    1      NaN      NaN      NaN  ...   
978     1    5    2.0  2.0    5.0    4    1      NaN      NaN      NaN  ...   
979     1   15    2.0  2.0    6.0    4    1      NaN      NaN      NaN  ...   
980     1   15    2.0  2.0   15.0    5    1      NaN      NaN      NaN  ...   
981     1    0    1.0  1.0    1.0    5    1      NaN      NaN      NaN  ...   
982     1   15    2.0  2.0   10.0    5    1      NaN      NaN      NaN  ...   
983     1   15    2.0  2.0   10.0    5    1      NaN      NaN      NaN  ...   
984     1   50    2.0  2.0   30.0    4    1      NaN      NaN      NaN  ...   
985     1   30    2.0  2.0   15.0    4    1      NaN      NaN      NaN  ...   
986     1   45    2.0  2.0   20.0    4    1      NaN      NaN      NaN  ...   
987     1   40    2.0  2.0   15.0    5    1      NaN      NaN      NaN  ...   
988     1   10    2.0  2.0    5.0    3    1      NaN      NaN      NaN  ...   
989     1   30    2.0  2.0   10.0    3    1      NaN      NaN      NaN  ...   
990     1   40    2.0  2.0   15.0    4    1      NaN      NaN      NaN  ...   
991     1   30    2.0  2.0   15.0    4    1      NaN      NaN      NaN  ...   
992     1   40    2.0  2.0   20.0    3    1      NaN    

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1004 entries, 0 to 1003
Data columns (total 55 columns):
sex                    1004 non-null int64
m32                    1004 non-null int64
m33_1                  920 non-null float64
PE                     816 non-null float64
m33_2                  816 non-null float64
m34                    1004 non-null int64
m35                    1004 non-null int64
m35_1_2                126 non-null float64
m35_2_2                43 non-null float64
m35_1_3                126 non-null float64
m35_2_3                46 non-null float64
m36_3                  133 non-null float64
m36_4                  133 non-null float64
m42                    1004 non-null int64
m43                    1004 non-null int64
m44                    1004 non-null int64
m45                    1004 non-null int64
m46                    1004 non-null int64
m47                    1004 non-null int64
m48                    1004 non-null int64
m49                    100

In [7]:
df = df.replace('\t','',regex=True)
df = df.replace(' ','',regex=True)
df = df.replace('\?','np.nan',regex=True)

## Data Cleaning

We determine and drop the variables with excessive missing values from the dataset.

In [8]:
def remove_bad_columns(df,bad_column_threshold):
    # find bad columns having too many missing values
    n_null = np.array(df.isnull().sum(axis=0))
    bad_col = np.array([]).astype(int)
    for i in range(len(n_null)):
        if n_null[i] >= bad_column_threshold:
            bad_col = np.append(bad_col,i)

    #print(bad_col)
    print('number of bad columns:',len(bad_col))

    # delete bad columns
    df = df.drop(df.columns[bad_col],axis=1)
    #df.info()
    return df   

In [9]:
df = remove_bad_columns(df,400)
df.info()

number of bad columns: 7
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1004 entries, 0 to 1003
Data columns (total 48 columns):
sex                    1004 non-null int64
m32                    1004 non-null int64
m33_1                  920 non-null float64
PE                     816 non-null float64
m33_2                  816 non-null float64
m34                    1004 non-null int64
m35                    1004 non-null int64
m42                    1004 non-null int64
m43                    1004 non-null int64
m44                    1004 non-null int64
m45                    1004 non-null int64
m46                    1004 non-null int64
m47                    1004 non-null int64
m48                    1004 non-null int64
m49                    1004 non-null int64
m50                    1004 non-null int64
m51                    1004 non-null int64
m52                    1004 non-null int64
m53                    1004 non-null int64
m54                    1004 non-null int64
m55  

In [10]:
# Find rows where target is missing
def find_missing_row_target(df):
    # find rows where target is missing
    missing_row = df['IIEF_Y_N'].isnull()
    print('Number of rows where target are missing:')
    print(sum(missing_row))

    #df = df[~missing_row]
    missing_row_indices = np.array([t for t in range(df.shape[0]) if missing_row[t]])
    
    return missing_row_indices

In [11]:
missing_row_target = find_missing_row_target(df)
print(missing_row_target)

Number of rows where target are missing:
238
[   0    1    2    3    8   13   18   20   25   38   48   50   52   53
   56   58   68   73   76   80   81   85   86   90   93   95   98  101
  107  121  124  125  127  130  133  135  137  153  156  157  158  159
  163  165  167  169  171  172  174  175  176  183  188  189  193  194
  196  200  202  214  215  217  221  225  227  228  232  234  238  243
  246  249  256  257  260  263  275  277  279  293  295  320  329  335
  345  347  355  360  361  377  382  387  394  395  408  424  428  429
  430  431  432  435  437  438  440  460  464  465  469  475  484  507
  528  537  539  540  541  542  544  559  563  564  566  569  571  576
  583  585  588  592  593  596  597  598  599  601  602  607  608  623
  630  633  634  641  644  655  661  666  667  669  670  672  673  674
  676  679  680  686  695  708  712  716  719  722  726  729  733  737
  738  749  751  752  753  754  756  757  758  759  760  761  762  770
  781  792  798  800  809  813  

We find bad rows which contain too many missing values.

In [12]:
def find_bad_rows(df,bad_row_threshold):   
    # find bad rows having too many missing values
    n_null = np.array(df.isnull().sum(axis=1))
    bad_row = np.array([]).astype(int)
    for t in range(len(n_null)):
        if n_null[t] >= bad_row_threshold:
            bad_row = np.append(bad_row,t)

    #print(bad_row)
    print('number of bad rows:',len(bad_row))

    # delete bad rows
    #df = df.drop(bad_row)
    #df.info()
    return bad_row

In [13]:
bad_row = find_bad_rows(df,5)
print(bad_row)

number of bad rows: 339
[   0    1    2    3    5    8   13   18   20   25   26   38   39   48
   50   52   53   56   58   63   68   73   76   80   81   85   86   87
   90   92   93   94   95   98  101  107  112  119  120  121  124  125
  127  130  133  135  136  137  153  156  157  158  159  163  165  167
  169  170  171  172  173  174  175  176  182  183  188  189  193  194
  196  200  202  203  210  214  215  217  221  222  225  227  228  232
  234  238  239  242  243  246  249  256  257  260  261  263  271  273
  275  277  278  279  281  292  293  294  295  297  298  303  320  329
  331  335  336  341  345  347  355  360  361  366  376  377  381  382
  383  384  387  394  395  405  408  412  413  414  419  424  428  429
  430  431  432  434  435  437  438  440  453  454  460  464  465  469
  470  473  475  479  481  484  485  487  490  495  505  507  509  512
  513  521  528  537  539  540  541  542  544  554  559  560  563  564
  565  566  568  569  571  572  574  576  578  583  5

In [14]:
del_row = np.union1d(missing_row_target,bad_row)
print(del_row)
df = df.drop(del_row)

[   0    1    2    3    5    8   13   18   20   25   26   38   39   48
   50   52   53   56   58   63   68   73   76   80   81   85   86   87
   90   92   93   94   95   98  101  107  112  119  120  121  124  125
  127  130  133  135  136  137  153  156  157  158  159  163  165  167
  169  170  171  172  173  174  175  176  182  183  188  189  193  194
  196  200  202  203  210  214  215  217  221  222  225  227  228  232
  234  238  239  242  243  246  249  256  257  260  261  263  271  273
  275  277  278  279  281  292  293  294  295  297  298  303  320  329
  331  335  336  341  345  347  355  360  361  366  376  377  381  382
  383  384  387  394  395  405  408  412  413  414  419  424  428  429
  430  431  432  434  435  437  438  440  453  454  460  464  465  469
  470  473  475  479  481  484  485  487  490  495  505  507  509  512
  513  521  528  537  539  540  541  542  544  554  559  560  563  564
  565  566  568  569  571  572  574  576  578  583  585  588  592  593
  596 

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 665 entries, 4 to 1002
Data columns (total 48 columns):
sex                    665 non-null int64
m32                    665 non-null int64
m33_1                  665 non-null float64
PE                     657 non-null float64
m33_2                  657 non-null float64
m34                    665 non-null int64
m35                    665 non-null int64
m42                    665 non-null int64
m43                    665 non-null int64
m44                    665 non-null int64
m45                    665 non-null int64
m46                    665 non-null int64
m47                    665 non-null int64
m48                    665 non-null int64
m49                    665 non-null int64
m50                    665 non-null int64
m51                    665 non-null int64
m52                    665 non-null int64
m53                    665 non-null int64
m54                    665 non-null int64
m55                    665 non-null int64
AGE   

For convenience, we separate independents `X` and dependent `y` from the data.

In [16]:
dfx = df.drop('IIEF_Y_N',axis=1)
dfy = df['IIEF_Y_N']

In [17]:
# number of uniques of each column (excluding NaN)
nu = np.array([len(pd.unique(dfx[col].dropna())) for col in dfx.columns])
print('number of uniques of each variable:')
print(nu)

number of uniques of each variable:
[ 1 29  3  2 25  7  3  5  6  5  6  5  5  6  6  6  6  5  5  5  5 60  6 18
  5  5  5  5  5 15  2 16 17  9  5  5  5  5  5  5  5  5  5  5  8  7  4]


In [18]:
def define_variable_type(df,nu):
    i_binary = [] ; i_category = [] ; i_continuous = []
    for i in range(len(nu)):
        if nu[i] == 2: # binary 
            i_binary.append(i)
        elif nu[i] < 5: # !!!! NOTE: this is not always correct, depending on data
            i_category.append(i)
        else:
            i_continuous.append(i)

    print('i_binary:',i_binary)
    print('i_category:',i_category)   
    #i_binary, i_category, i_continuous
    
    variable_type  = np.ones(len(nu))  # binary
    variable_type[i_category] = 2   # categorical
    variable_type[i_continuous] = 3 # continuous

    return variable_type #,i_binary,i_category,i_continuous

In [19]:
variable_type = define_variable_type(dfx,nu)
print('variable type:',variable_type)

i_binary: [3, 30]
i_category: [0, 2, 6, 46]
variable type: [2. 3. 2. 1. 3. 3. 2. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.
 3. 3. 3. 3. 3. 3. 1. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 2.]


In [20]:
def impute_missing(df,variable_type):
    # impute binary and categorical variables by the most frequency (in each column)
    # continuous variable by median
    # input: df: pandas data frame, variable_type: list
    # output: df2: pandas data frame
    df2 = df.copy()
    for i,col in enumerate(df.columns):
        if variable_type[i] < 3: # binary or caterogy
            df2[col] = df[col].fillna(df[col].mode().iloc[0])
        else: # continuous
            df2[col] = df[col].fillna(df[col].median())    
    return df2       

In [21]:
dfx_imputed = impute_missing(dfx,variable_type)
dfx_imputed

sex  m32  m33_1   PE  m33_2  m34  m35  m42  m43  m44  ...  IPE4  IPE5  \
4       1   60    2.0  2.0   45.0    5    1    1    1    1  ...   5.0   4.0   
6       1    5    2.0  2.0    2.0    3    1    2    2    2  ...   4.0   4.0   
7       1   10    2.0  2.0    5.0    4    1    1    2    2  ...   4.0   3.0   
9       1   30    2.0  2.0  999.0    5    1    1    1    1  ...   5.0   5.0   
10      1    6    2.0  2.0    5.0    4    2    1    1    1  ...   5.0   5.0   
11      1    5    2.0  2.0    5.0    4    1    2    3    1  ...   4.0   4.0   
12      1   10    2.0  2.0   10.0    5    1    1    2    2  ...   4.0   5.0   
14      1    5    2.0  2.0    5.0    4    1    1    1    1  ...   5.0   5.0   
15      1   10    2.0  2.0    8.0    3    1    3    3    2  ...   4.0   4.0   
16      1   15    2.0  2.0   10.0    4    1    1    1    1  ...   5.0   5.0   
17      1   15    2.0  2.0    8.0    4    1    1    1    1  ...   5.0   5.0   
19      1    2    2.0  2.0    2.0    5    1    5    1    1  ...   5.0   5.0   
21      1   30    2.0  2.0   10.0    4    1    1    1    1  ...   1.0   1.0   
22      1    5    2.0  2.0    3.0    5    1    1    2    1  ...   5.0   4.0   
23      1   10    2.0  2.0   10.0    5    1    1    2    1  ...   5.0   5.0   
24      1    3    2.0  2.0    2.0    5    1    1    2    1  ...   4.0   4.0   
27      1    5    2.0  2.0    5.0    5    1    1    1    1  ...   5.0   5.0   
28      1   10    2.0  2.0    8.0    5    1    1    2    1  ...   5.0   4.0   
29      1   20    2.0  2.0   20.0    5    1    1    2    1  ...   5.0   5.0   
30      1   10    2.0  2.0   10.0    5    1    1    1    1  ...   5.0   5.0   
31      1   15    2.0  2.0    7.0    5    1    1    1    1  ...   5.0   5.0   
32      1   10    2.0  2.0    5.0    5    1    1    2    1  ...   4.0   4.0   
33      1   12    2.0  2.0    8.0    6    1    3    2    1  ...   5.0   5.0   
34      1    5    2.0  2.0    3.0    5    2    2    4    2  ...   3.0   2.0   
35      1   15    2.0  2.0   10.0    4    1    4    3    1  ...   3.0   4.0   
36      1   15    2.0  2.0   12.0    5    2    4    4    4  ...   2.0   2.0   
37      1   20    2.0  2.0   10.0    5    1    2    2    1  ...   4.0   5.0   
40      1   30    2.0  2.0   30.0    5    1    1    1    1  ...   5.0   4.0   
41      1   30    2.0  2.0   20.0    5    1    3    2    1  ...   5.0   5.0   
42      1    5    2.0  2.0    5.0    4    1    1    1    1  ...   5.0   5.0   
...   ...  ...    ...  ...    ...  ...  ...  ...  ...  ...  ...   ...   ...   
961     1   10    2.0  2.0   10.0    5    1    1    1    1  ...   4.0   4.0   
962     1   10    2.0  2.0    5.0    3    1    1    2    1  ...   5.0   4.0   
965     1   15    2.0  2.0   15.0    5    1    1    1    1  ...   5.0   5.0   
966     1   20    2.0  2.0   10.0    4    1    1    1    4  ...   4.0   3.0   
967     1   30    2.0  2.0   20.0    5    1    5    1    1  ...   4.0   5.0   
968     1   20    2.0  2.0   15.0    4    1    1    2    1  ...   4.0   5.0   
969     1   10    2.0  2.0   10.0    4    1    3    3    1  ...   3.0   2.0   
970     1   20    2.0  2.0   20.0    4    1    1    2    1  ...   5.0   4.0   
971     1   15    2.0  2.0   15.0    2    1    2    1    1  ...   5.0   5.0   
973     1    3    2.0  2.0    3.0    4    1    1    2    2  ...   5.0   4.0   
976     1   10    2.0  2.0    8.0    6    1    1    1    1  ...   5.0   5.0   
977     1   10    2.0  2.0    5.0    5    1    1    1    1  ...   5.0   5.0   
978     1    5    2.0  2.0    5.0    4    1    1    2    1  ...   4.0   4.0   
979     1   15    2.0  2.0    6.0    4    1    1    1    1  ...   5.0   4.0   
982     1   15    2.0  2.0   10.0    5    1    1    1    1  ...   5.0   4.0   
984     1   50    2.0  2.0   30.0    4    1    5    1    1  ...   5.0   4.0   
985     1   30    2.0  2.0   15.0    4    1    3    2    1  ...   4.0   5.0   
986     1   45    2.0  2.0   20.0    4    1    3    2    3  ...   4.0   4.0   
987     1   40    2.0  2.0   15.0    5    1    2    2   

In [22]:
dfx_imputed.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 665 entries, 4 to 1002
Data columns (total 47 columns):
sex                    665 non-null int64
m32                    665 non-null int64
m33_1                  665 non-null float64
PE                     665 non-null float64
m33_2                  665 non-null float64
m34                    665 non-null int64
m35                    665 non-null int64
m42                    665 non-null int64
m43                    665 non-null int64
m44                    665 non-null int64
m45                    665 non-null int64
m46                    665 non-null int64
m47                    665 non-null int64
m48                    665 non-null int64
m49                    665 non-null int64
m50                    665 non-null int64
m51                    665 non-null int64
m52                    665 non-null int64
m53                    665 non-null int64
m54                    665 non-null int64
m55                    665 non-null int64
AGE   

## Data Processing

### Attributes

In [23]:
def convert_binary_and_category(x,variable_type):
    """
    convert binary to +-1, category to one hot; remain continuous.
    """
    
    onehot_encoder = OneHotEncoder(sparse=False,categories='auto')

    # create 2 initial columns
    x_new = np.zeros((x.shape[0],2))

    for i,i_type in enumerate(variable_type):
        if i_type == 1: # binary
            unique_value = np.unique(x[:,i])
            x1 = np.array([-1. if value == unique_value[0] else 1. for value in x[:,i]])        
            x_new = np.hstack((x_new,x1[:,np.newaxis]))

        elif i_type == 2: # category
            x1 = onehot_encoder.fit_transform(x[:,i].reshape(-1,1))
            x_new = np.hstack((x_new,x1))
            
        else: # continuous      
            x_new = np.hstack((x_new,x[:,i][:,np.newaxis]))      

    # drop the 2 initial column
    x_new = x_new[:,2:]
    
    return x_new.astype(float)

In [24]:
# convert x
x = np.array(dfx_imputed)
x_new = convert_binary_and_category(x,variable_type)

print(x_new.shape)
print(x_new)

(665, 54)
[[ 1. 60.  0. ...  1.  0.  0.]
 [ 1.  5.  0. ...  1.  0.  0.]
 [ 1. 10.  0. ...  1.  0.  0.]
 ...
 [ 1. 45.  0. ...  1.  0.  0.]
 [ 1. 30.  0. ...  1.  0.  0.]
 [ 1. 10.  0. ...  1.  0.  0.]]


### Target

In [25]:
y = np.array(dfy)
print(np.unique(y,return_counts=True))

# convert target to 0 and 1
y_new = np.ones(y.shape[0])
y_new[y ==2] = 0

# if target is already 0 and 1
#y_new = y #and delete lines below convert  
print(np.unique(y_new,return_counts=True))

(array([1., 2.]), array([572,  93]))
(array([0., 1.]), array([ 93, 572]))


In [26]:
# combine X and y and save to a file
xy_new = np.hstack((x_new,y_new[:,np.newaxis]))
np.savetxt('ef_processed.dat',xy_new,fmt='%f')