In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
#from sklearn.preprocessing import Imputer

In [2]:
np.random.seed(1)

In [3]:
df = pd.read_csv("stigma.csv")
df

ID  Y1  Y2  Y3  Y4  C01  C02  C03  C04  C05  ...  X1  X2  X3  X4  \
0           1   1   0   1   0    0    0    0    1    0  ...   1   1   1   0   
1           2   0   0   1   1    1    1    1    1    1  ...   1   0   1   1   
2           4   1   1   1   0    0    1    0    1    1  ...   0   0   1   1   
3           5   0   0   0   0    1    1    1    1    1  ...   1   0   1   1   
4           6   0   1   1   1    1    1    1    1    1  ...   0   0   1   0   
5           7   1   1   1   1    1    1    0    1    0  ...   0   1   1   0   
6           8   1   1   1   0    0    0    0    1    1  ...   0   1   1   1   
7           9   1   0   1   0    1    1    0    1    1  ...   0   0   1   1   
8          11   1   0   0   0    0    1    1    1    1  ...   1   0   1   0   
9          12   1   1   1   0    1    1    0    0    0  ...   1   0   1   0   
10         13   0   1   1   1    1    1    1    1    1  ...   1   1   1   0   
11         14   0   1   1   0    1    1    1    1    1  ...   1   1   1   1   
12         15   1   1   1   0    0    1    1    1    0  ...   0   0   1   1   
13         16   0   1   0   0    1    1    1    1    1  ...   1   0   1   0   
14         18   0   1   0   0    1    1    1    1    1  ...   0   0   0   1   
15         19   0   0   1   0    1    1    1    1    1  ...   0   1   1   1   
16         21   1   1   1   0    0    1    0    0    0  ...   1   0   1   1   
17         24   1   0   0   0    1    1    0    0    0  ...   1   0   0   0   
18         25   0   0   0   0    1    1    1    1    1  ...   1   0   1   1   
19         26   1   0   0   0    0    1    0    0    0  ...   0   0   1   1   
20         27   0   0   0   0    1    1    1    1    1  ...   0   1   1   1   
21         28   0   0   1   0    1    1    1    1    1  ...   0   0   1   1   
22         29   1   0   1   0    0    1    0    0    0  ...   0   0   0   1   
23         33   1   1   1   1    0    0    0    0    0  ...   1   0   1   1   
24         34   1   1   1   0    0    0    0    0    0  ...   0   0   0   0   
25         35   0   0   0   0    1    1    1    1    1  ...   1   0   1   1   
26         36   0   1   1   0    1    1    1    1    1  ...   0   1   1   1   
27         38   1   0   1   1    1    1    1    1    1  ...   1   0   1   1   
28         39   1   1   1   0    0    0    0    0    0  ...   1   1   1   1   
29         40   0   1   1   1    1    1    1    1    1  ...   0   0   1   1   
...       ...  ..  ..  ..  ..  ...  ...  ...  ...  ...  ...  ..  ..  ..  ..   
10635  12,707   1   1   1   1    0    1    0    1    1  ...   1   0   1   1   
10636  12,708   1   1   1   0    0    1    0    0    0  ...   0   0   0   1   
10637  12,709   1   1   1   0    0    1    1    1    1  ...   0   0   1   1   
10638  12,710   1   1   1   1    0    0    1    1    1  ...   0   0   1   1   
10639  12,711   0   0   1   0    1    1    1    1    1  ...   0   0   1   1   
10640  12,712   0   0   0   0    1    1    1    1    1  ...   0   1   1   1   
10641  12,713   1   1   1   1    0    0    0    0    0  ...   0   1   0   0   
10642  12,714   1   0   1   0    0    1    0    1    0  ...   0   0   1   1   
10643  12,715   1   1   1   1    1    0    1    1    1  ...   0   0   0   0   
10644  12,716   1   1   0   0    1    1    1    0    1  ...   0   0   1   1   
10645  12,718   1   1   1   1    0    0    0    0    0  ...   1   0   1   0   
10646  12,719   1   0   1   0    0    1    0    1    1  ...   0   0   1   1   
10647  12,720   0   0   0   0    1    1    1    1    1  ...   0   0   0   1   
10648  12,721   1   1   1   1    0    1    0    0    0  ...   0   0   1   0   
10649  12,722   0   0   0   0    1    1    1    1    1  ...   1   1   1   1   
10650  12,723   0   0   1   0    1    1    1    1    1  ...   1   1   1   1   
10651  12,724   0   1   1   0    1    1    1    1    1  ...   0   0   1   0   
10652  12,725   1   0   1   1    1    1    0    1    1  ...   0   1   0   1   
10653  12,726   1   1   1   1    0    0    0    0    0  ...  

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10665 entries, 0 to 10664
Data columns (total 39 columns):
ID             10665 non-null object
Y1             10665 non-null int64
Y2             10665 non-null int64
Y3             10665 non-null int64
Y4             10665 non-null int64
C01            10665 non-null int64
C02            10665 non-null int64
C03            10665 non-null int64
C04            10665 non-null int64
C05            10665 non-null int64
C06            10665 non-null int64
C07            10665 non-null int64
C08            10665 non-null int64
C09            10665 non-null int64
C10            10665 non-null int64
C11            10665 non-null int64
C12            10665 non-null int64
C13            10665 non-null int64
C14            10665 non-null int64
C15            10665 non-null int64
C16            10665 non-null int64
C17            10665 non-null int64
C18            10665 non-null int64
C19            10665 non-null int64
C20            10665 non-n

## Data Cleaning

In [5]:
# Drop the column `ID` as it is unrelated to the dependent variable
df = df.drop(['ID','Unnamed: 38'],axis=1)
df

Y1  Y2  Y3  Y4  C01  C02  C03  C04  C05  C06  ...  C24  X1  X2  X3  X4  \
0       1   0   1   0    0    0    0    1    0    1  ...    1   1   1   1   0   
1       0   0   1   1    1    1    1    1    1    1  ...    0   1   0   1   1   
2       1   1   1   0    0    1    0    1    1    0  ...    1   0   0   1   1   
3       0   0   0   0    1    1    1    1    1    1  ...    1   1   0   1   1   
4       0   1   1   1    1    1    1    1    1    1  ...    1   0   0   1   0   
5       1   1   1   1    1    1    0    1    0    0  ...    0   0   1   1   0   
6       1   1   1   0    0    0    0    1    1    0  ...    1   0   1   1   1   
7       1   0   1   0    1    1    0    1    1    1  ...    1   0   0   1   1   
8       1   0   0   0    0    1    1    1    1    0  ...    1   1   0   1   0   
9       1   1   1   0    1    1    0    0    0    1  ...    1   1   0   1   0   
10      0   1   1   1    1    1    1    1    1    1  ...    0   1   1   1   0   
11      0   1   1   0    1    1    1    1    1    1  ...    1   1   1   1   1   
12      1   1   1   0    0    1    1    1    0    0  ...    1   0   0   1   1   
13      0   1   0   0    1    1    1    1    1    1  ...    1   1   0   1   0   
14      0   1   0   0    1    1    1    1    1    1  ...    1   0   0   0   1   
15      0   0   1   0    1    1    1    1    1    1  ...    1   0   1   1   1   
16      1   1   1   0    0    1    0    0    0    1  ...    1   1   0   1   1   
17      1   0   0   0    1    1    0    0    0    1  ...    1   1   0   0   0   
18      0   0   0   0    1    1    1    1    1    1  ...    1   1   0   1   1   
19      1   0   0   0    0    1    0    0    0    1  ...    1   0   0   1   1   
20      0   0   0   0    1    1    1    1    1    1  ...    1   0   1   1   1   
21      0   0   1   0    1    1    1    1    1    1  ...    1   0   0   1   1   
22      1   0   1   0    0    1    0    0    0    1  ...    1   0   0   0   1   
23      1   1   1   1    0    0    0    0    0    1  ...    0   1   0   1   1   
24      1   1   1   0    0    0    0    0    0    0  ...    1   0   0   0   0   
25      0   0   0   0    1    1    1    1    1    1  ...    1   1   0   1   1   
26      0   1   1   0    1    1    1    1    1    1  ...    1   0   1   1   1   
27      1   0   1   1    1    1    1    1    1    0  ...    0   1   0   1   1   
28      1   1   1   0    0    0    0    0    0    1  ...    1   1   1   1   1   
29      0   1   1   1    1    1    1    1    1    1  ...    0   0   0   1   1   
...    ..  ..  ..  ..  ...  ...  ...  ...  ...  ...  ...  ...  ..  ..  ..  ..   
10635   1   1   1   1    0    1    0    1    1    1  ...    0   1   0   1   1   
10636   1   1   1   0    0    1    0    0    0    0  ...    1   0   0   0   1   
10637   1   1   1   0    0    1    1    1    1    1  ...    1   0   0   1   1   
10638   1   1   1   1    0    0    1    1    1    0  ...    0   0   0   1   1   
10639   0   0   1   0    1    1    1    1    1    1  ...    1   0   0   1   1   
10640   0   0   0   0    1    1    1    1    1    1  ...    1   0   1   1   1   
10641   1   1   1   1    0    0    0    0    0    0  ...    0   0   1   0   0   
10642   1   0   1   0    0    1    0    1    0    1  ...    1   0   0   1   1   
10643   1   1   1   1    1    0    1    1    1    0  ...    0   0   0   0   0   
10644   1   1   0   0    1    1    1    0    1    1  ...    1   0   0   1   1   
10645   1   1   1   1    0    0    0    0    0    0  ...    0   1   0   1   0   
10646   1   0   1   0    0    1    0    1    1    1  ...    1   0   0   1   1   
10647   0   0   0   0    1    1    1    1    1    1  ...    1   0   0   0   1   
10648   1   1   1   1    0    1    0    0    0    0  ...    0   0   0   1   0   
10649   0   0   0   0    1    1    1    1    1    1  ...    1   1   1   1   1   
10650   0   0   1   0    1    1    1    1    1    1  ...    1   1   1   1   1   
10651   0   1   1   0    1    1    1    1    1    1  ...    1   0   0   1   0   
10652   1   0   1   1    1    1    0  

In [6]:
# Remove rows where taget are missing
missing_row = df['Y1'].isnull()
print('Number of rows where target are missing:')
print(sum(missing_row))

df = df[~missing_row]
df

Number of rows where target are missing:
0


Y1  Y2  Y3  Y4  C01  C02  C03  C04  C05  C06  ...  C24  X1  X2  X3  X4  \
0       1   0   1   0    0    0    0    1    0    1  ...    1   1   1   1   0   
1       0   0   1   1    1    1    1    1    1    1  ...    0   1   0   1   1   
2       1   1   1   0    0    1    0    1    1    0  ...    1   0   0   1   1   
3       0   0   0   0    1    1    1    1    1    1  ...    1   1   0   1   1   
4       0   1   1   1    1    1    1    1    1    1  ...    1   0   0   1   0   
5       1   1   1   1    1    1    0    1    0    0  ...    0   0   1   1   0   
6       1   1   1   0    0    0    0    1    1    0  ...    1   0   1   1   1   
7       1   0   1   0    1    1    0    1    1    1  ...    1   0   0   1   1   
8       1   0   0   0    0    1    1    1    1    0  ...    1   1   0   1   0   
9       1   1   1   0    1    1    0    0    0    1  ...    1   1   0   1   0   
10      0   1   1   1    1    1    1    1    1    1  ...    0   1   1   1   0   
11      0   1   1   0    1    1    1    1    1    1  ...    1   1   1   1   1   
12      1   1   1   0    0    1    1    1    0    0  ...    1   0   0   1   1   
13      0   1   0   0    1    1    1    1    1    1  ...    1   1   0   1   0   
14      0   1   0   0    1    1    1    1    1    1  ...    1   0   0   0   1   
15      0   0   1   0    1    1    1    1    1    1  ...    1   0   1   1   1   
16      1   1   1   0    0    1    0    0    0    1  ...    1   1   0   1   1   
17      1   0   0   0    1    1    0    0    0    1  ...    1   1   0   0   0   
18      0   0   0   0    1    1    1    1    1    1  ...    1   1   0   1   1   
19      1   0   0   0    0    1    0    0    0    1  ...    1   0   0   1   1   
20      0   0   0   0    1    1    1    1    1    1  ...    1   0   1   1   1   
21      0   0   1   0    1    1    1    1    1    1  ...    1   0   0   1   1   
22      1   0   1   0    0    1    0    0    0    1  ...    1   0   0   0   1   
23      1   1   1   1    0    0    0    0    0    1  ...    0   1   0   1   1   
24      1   1   1   0    0    0    0    0    0    0  ...    1   0   0   0   0   
25      0   0   0   0    1    1    1    1    1    1  ...    1   1   0   1   1   
26      0   1   1   0    1    1    1    1    1    1  ...    1   0   1   1   1   
27      1   0   1   1    1    1    1    1    1    0  ...    0   1   0   1   1   
28      1   1   1   0    0    0    0    0    0    1  ...    1   1   1   1   1   
29      0   1   1   1    1    1    1    1    1    1  ...    0   0   0   1   1   
...    ..  ..  ..  ..  ...  ...  ...  ...  ...  ...  ...  ...  ..  ..  ..  ..   
10635   1   1   1   1    0    1    0    1    1    1  ...    0   1   0   1   1   
10636   1   1   1   0    0    1    0    0    0    0  ...    1   0   0   0   1   
10637   1   1   1   0    0    1    1    1    1    1  ...    1   0   0   1   1   
10638   1   1   1   1    0    0    1    1    1    0  ...    0   0   0   1   1   
10639   0   0   1   0    1    1    1    1    1    1  ...    1   0   0   1   1   
10640   0   0   0   0    1    1    1    1    1    1  ...    1   0   1   1   1   
10641   1   1   1   1    0    0    0    0    0    0  ...    0   0   1   0   0   
10642   1   0   1   0    0    1    0    1    0    1  ...    1   0   0   1   1   
10643   1   1   1   1    1    0    1    1    1    0  ...    0   0   0   0   0   
10644   1   1   0   0    1    1    1    0    1    1  ...    1   0   0   1   1   
10645   1   1   1   1    0    0    0    0    0    0  ...    0   1   0   1   0   
10646   1   0   1   0    0    1    0    1    1    1  ...    1   0   0   1   1   
10647   0   0   0   0    1    1    1    1    1    1  ...    1   0   0   0   1   
10648   1   1   1   1    0    1    0    0    0    0  ...    0   0   0   1   0   
10649   0   0   0   0    1    1    1    1    1    1  ...    1   1   1   1   1   
10650   0   0   1   0    1    1    1    1    1    1  ...    1   1   1   1   1   
10651   0   1   1   0    1    1    1    1    1    1  ...    1   0   0   1   0   
10652   1   0   1   1    1    1    0  

We determine and drop the variables with excessive missing values from the dataset.

In [7]:
def remove_bad_columns(df,bad_column_threshold):
    # find bad columns having too many missing values
    n_null = np.array(df.isnull().sum(axis=0))
    bad_col = np.array([]).astype(int)
    for i in range(len(n_null)):
        if n_null[i] >= bad_column_threshold:
            bad_col = np.append(bad_col,i)

    #print(bad_col)
    print('number of bad columns:',len(bad_col))

    # delete bad columns
    df = df.drop(df.columns[bad_col],axis=1)
    #df.info()
    return df   

In [8]:
df = remove_bad_columns(df,10)
df

number of bad columns: 0


Y1  Y2  Y3  Y4  C01  C02  C03  C04  C05  C06  ...  C24  X1  X2  X3  X4  \
0       1   0   1   0    0    0    0    1    0    1  ...    1   1   1   1   0   
1       0   0   1   1    1    1    1    1    1    1  ...    0   1   0   1   1   
2       1   1   1   0    0    1    0    1    1    0  ...    1   0   0   1   1   
3       0   0   0   0    1    1    1    1    1    1  ...    1   1   0   1   1   
4       0   1   1   1    1    1    1    1    1    1  ...    1   0   0   1   0   
5       1   1   1   1    1    1    0    1    0    0  ...    0   0   1   1   0   
6       1   1   1   0    0    0    0    1    1    0  ...    1   0   1   1   1   
7       1   0   1   0    1    1    0    1    1    1  ...    1   0   0   1   1   
8       1   0   0   0    0    1    1    1    1    0  ...    1   1   0   1   0   
9       1   1   1   0    1    1    0    0    0    1  ...    1   1   0   1   0   
10      0   1   1   1    1    1    1    1    1    1  ...    0   1   1   1   0   
11      0   1   1   0    1    1    1    1    1    1  ...    1   1   1   1   1   
12      1   1   1   0    0    1    1    1    0    0  ...    1   0   0   1   1   
13      0   1   0   0    1    1    1    1    1    1  ...    1   1   0   1   0   
14      0   1   0   0    1    1    1    1    1    1  ...    1   0   0   0   1   
15      0   0   1   0    1    1    1    1    1    1  ...    1   0   1   1   1   
16      1   1   1   0    0    1    0    0    0    1  ...    1   1   0   1   1   
17      1   0   0   0    1    1    0    0    0    1  ...    1   1   0   0   0   
18      0   0   0   0    1    1    1    1    1    1  ...    1   1   0   1   1   
19      1   0   0   0    0    1    0    0    0    1  ...    1   0   0   1   1   
20      0   0   0   0    1    1    1    1    1    1  ...    1   0   1   1   1   
21      0   0   1   0    1    1    1    1    1    1  ...    1   0   0   1   1   
22      1   0   1   0    0    1    0    0    0    1  ...    1   0   0   0   1   
23      1   1   1   1    0    0    0    0    0    1  ...    0   1   0   1   1   
24      1   1   1   0    0    0    0    0    0    0  ...    1   0   0   0   0   
25      0   0   0   0    1    1    1    1    1    1  ...    1   1   0   1   1   
26      0   1   1   0    1    1    1    1    1    1  ...    1   0   1   1   1   
27      1   0   1   1    1    1    1    1    1    0  ...    0   1   0   1   1   
28      1   1   1   0    0    0    0    0    0    1  ...    1   1   1   1   1   
29      0   1   1   1    1    1    1    1    1    1  ...    0   0   0   1   1   
...    ..  ..  ..  ..  ...  ...  ...  ...  ...  ...  ...  ...  ..  ..  ..  ..   
10635   1   1   1   1    0    1    0    1    1    1  ...    0   1   0   1   1   
10636   1   1   1   0    0    1    0    0    0    0  ...    1   0   0   0   1   
10637   1   1   1   0    0    1    1    1    1    1  ...    1   0   0   1   1   
10638   1   1   1   1    0    0    1    1    1    0  ...    0   0   0   1   1   
10639   0   0   1   0    1    1    1    1    1    1  ...    1   0   0   1   1   
10640   0   0   0   0    1    1    1    1    1    1  ...    1   0   1   1   1   
10641   1   1   1   1    0    0    0    0    0    0  ...    0   0   1   0   0   
10642   1   0   1   0    0    1    0    1    0    1  ...    1   0   0   1   1   
10643   1   1   1   1    1    0    1    1    1    0  ...    0   0   0   0   0   
10644   1   1   0   0    1    1    1    0    1    1  ...    1   0   0   1   1   
10645   1   1   1   1    0    0    0    0    0    0  ...    0   1   0   1   0   
10646   1   0   1   0    0    1    0    1    1    1  ...    1   0   0   1   1   
10647   0   0   0   0    1    1    1    1    1    1  ...    1   0   0   0   1   
10648   1   1   1   1    0    1    0    0    0    0  ...    0   0   0   1   0   
10649   0   0   0   0    1    1    1    1    1    1  ...    1   1   1   1   1   
10650   0   0   1   0    1    1    1    1    1    1  ...    1   1   1   1   1   
10651   0   1   1   0    1    1    1    1    1    1  ...    1   0   0   1   0   
10652   1   0   1   1    1    1    0  

We find bad rows which contain too many missing values, then remove them.

In [9]:
def remove_bad_rows(df,bad_row_threshold):   
    # find bad rows having too many missing values
    n_null = np.array(df.isnull().sum(axis=1))
    bad_row = np.array([]).astype(int)
    for t in range(len(n_null)):
        if n_null[t] >= bad_row_threshold:
            bad_row = np.append(bad_row,t)

    #print(bad_row)
    print('number of bad rows:',len(bad_row))

    # delete bad rows
    df = df.drop(bad_row)
    #df.info()
    return df

In [10]:
df = remove_bad_rows(df,3)
df

number of bad rows: 0


Y1  Y2  Y3  Y4  C01  C02  C03  C04  C05  C06  ...  C24  X1  X2  X3  X4  \
0       1   0   1   0    0    0    0    1    0    1  ...    1   1   1   1   0   
1       0   0   1   1    1    1    1    1    1    1  ...    0   1   0   1   1   
2       1   1   1   0    0    1    0    1    1    0  ...    1   0   0   1   1   
3       0   0   0   0    1    1    1    1    1    1  ...    1   1   0   1   1   
4       0   1   1   1    1    1    1    1    1    1  ...    1   0   0   1   0   
5       1   1   1   1    1    1    0    1    0    0  ...    0   0   1   1   0   
6       1   1   1   0    0    0    0    1    1    0  ...    1   0   1   1   1   
7       1   0   1   0    1    1    0    1    1    1  ...    1   0   0   1   1   
8       1   0   0   0    0    1    1    1    1    0  ...    1   1   0   1   0   
9       1   1   1   0    1    1    0    0    0    1  ...    1   1   0   1   0   
10      0   1   1   1    1    1    1    1    1    1  ...    0   1   1   1   0   
11      0   1   1   0    1    1    1    1    1    1  ...    1   1   1   1   1   
12      1   1   1   0    0    1    1    1    0    0  ...    1   0   0   1   1   
13      0   1   0   0    1    1    1    1    1    1  ...    1   1   0   1   0   
14      0   1   0   0    1    1    1    1    1    1  ...    1   0   0   0   1   
15      0   0   1   0    1    1    1    1    1    1  ...    1   0   1   1   1   
16      1   1   1   0    0    1    0    0    0    1  ...    1   1   0   1   1   
17      1   0   0   0    1    1    0    0    0    1  ...    1   1   0   0   0   
18      0   0   0   0    1    1    1    1    1    1  ...    1   1   0   1   1   
19      1   0   0   0    0    1    0    0    0    1  ...    1   0   0   1   1   
20      0   0   0   0    1    1    1    1    1    1  ...    1   0   1   1   1   
21      0   0   1   0    1    1    1    1    1    1  ...    1   0   0   1   1   
22      1   0   1   0    0    1    0    0    0    1  ...    1   0   0   0   1   
23      1   1   1   1    0    0    0    0    0    1  ...    0   1   0   1   1   
24      1   1   1   0    0    0    0    0    0    0  ...    1   0   0   0   0   
25      0   0   0   0    1    1    1    1    1    1  ...    1   1   0   1   1   
26      0   1   1   0    1    1    1    1    1    1  ...    1   0   1   1   1   
27      1   0   1   1    1    1    1    1    1    0  ...    0   1   0   1   1   
28      1   1   1   0    0    0    0    0    0    1  ...    1   1   1   1   1   
29      0   1   1   1    1    1    1    1    1    1  ...    0   0   0   1   1   
...    ..  ..  ..  ..  ...  ...  ...  ...  ...  ...  ...  ...  ..  ..  ..  ..   
10635   1   1   1   1    0    1    0    1    1    1  ...    0   1   0   1   1   
10636   1   1   1   0    0    1    0    0    0    0  ...    1   0   0   0   1   
10637   1   1   1   0    0    1    1    1    1    1  ...    1   0   0   1   1   
10638   1   1   1   1    0    0    1    1    1    0  ...    0   0   0   1   1   
10639   0   0   1   0    1    1    1    1    1    1  ...    1   0   0   1   1   
10640   0   0   0   0    1    1    1    1    1    1  ...    1   0   1   1   1   
10641   1   1   1   1    0    0    0    0    0    0  ...    0   0   1   0   0   
10642   1   0   1   0    0    1    0    1    0    1  ...    1   0   0   1   1   
10643   1   1   1   1    1    0    1    1    1    0  ...    0   0   0   0   0   
10644   1   1   0   0    1    1    1    0    1    1  ...    1   0   0   1   1   
10645   1   1   1   1    0    0    0    0    0    0  ...    0   1   0   1   0   
10646   1   0   1   0    0    1    0    1    1    1  ...    1   0   0   1   1   
10647   0   0   0   0    1    1    1    1    1    1  ...    1   0   0   0   1   
10648   1   1   1   1    0    1    0    0    0    0  ...    0   0   0   1   0   
10649   0   0   0   0    1    1    1    1    1    1  ...    1   1   1   1   1   
10650   0   0   1   0    1    1    1    1    1    1  ...    1   1   1   1   1   
10651   0   1   1   0    1    1    1    1    1    1  ...    1   0   0   1   0   
10652   1   0   1   1    1    1    0  

In [11]:
dfx = df.drop('Y1',axis=1)
dfy = df['Y1']

In [12]:
# number of uniques of each column (excluding NaN)
nu = np.array([len(pd.unique(dfx[col].dropna())) for col in dfx.columns])
print('number of uniques of each variable:')
print(nu)

number of uniques of each variable:
[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


In [13]:
def define_variable_type(df,nu):
    i_binary = [] ; i_category = [] ; i_continuous = []
    for i in range(len(nu)):
        if nu[i] == 2: # binary 
            i_binary.append(i)
        elif nu[i] < 5: # !!!! NOTE: this is not always correct, depending on data
            i_category.append(i)
        else:
            i_continuous.append(i)

    print('i_binary:',i_binary)
    print('i_category:',i_category)   
    #i_binary, i_category, i_continuous
    
    variable_type  = np.ones(len(nu))  # binary
    variable_type[i_category] = 2   # categorical
    variable_type[i_continuous] = 3 # continuous

    return variable_type #,i_binary,i_category,i_continuous

In [14]:
variable_type = define_variable_type(dfx,nu)
print('variable type:',variable_type)

i_binary: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]
i_category: []
variable type: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [15]:
def impute_missing(df,variable_type):
    # impute binary and categorical variables by the most frequency (in each column)
    # continuous variable by median
    # input: df: pandas data frame, variable_type: list
    # output: df2: pandas data frame
    df2 = df.copy()
    for i,col in enumerate(df.columns):
        if variable_type[i] < 3: # binary or caterogy
            df2[col] = df[col].fillna(df[col].mode().iloc[0])
        else: # continuous
            df2[col] = df[col].fillna(df[col].median())    
    return df2       

In [16]:
dfx_imputed = impute_missing(dfx,variable_type)
dfx_imputed

Y2  Y3  Y4  C01  C02  C03  C04  C05  C06  C07  ...  C24  X1  X2  X3  \
0       0   1   0    0    0    0    1    0    1    1  ...    1   1   1   1   
1       0   1   1    1    1    1    1    1    1    1  ...    0   1   0   1   
2       1   1   0    0    1    0    1    1    0    1  ...    1   0   0   1   
3       0   0   0    1    1    1    1    1    1    1  ...    1   1   0   1   
4       1   1   1    1    1    1    1    1    1    0  ...    1   0   0   1   
5       1   1   1    1    1    0    1    0    0    1  ...    0   0   1   1   
6       1   1   0    0    0    0    1    1    0    1  ...    1   0   1   1   
7       0   1   0    1    1    0    1    1    1    1  ...    1   0   0   1   
8       0   0   0    0    1    1    1    1    0    1  ...    1   1   0   1   
9       1   1   0    1    1    0    0    0    1    0  ...    1   1   0   1   
10      1   1   1    1    1    1    1    1    1    1  ...    0   1   1   1   
11      1   1   0    1    1    1    1    1    1    1  ...    1   1   1   1   
12      1   1   0    0    1    1    1    0    0    1  ...    1   0   0   1   
13      1   0   0    1    1    1    1    1    1    0  ...    1   1   0   1   
14      1   0   0    1    1    1    1    1    1    0  ...    1   0   0   0   
15      0   1   0    1    1    1    1    1    1    1  ...    1   0   1   1   
16      1   1   0    0    1    0    0    0    1    1  ...    1   1   0   1   
17      0   0   0    1    1    0    0    0    1    1  ...    1   1   0   0   
18      0   0   0    1    1    1    1    1    1    1  ...    1   1   0   1   
19      0   0   0    0    1    0    0    0    1    1  ...    1   0   0   1   
20      0   0   0    1    1    1    1    1    1    1  ...    1   0   1   1   
21      0   1   0    1    1    1    1    1    1    1  ...    1   0   0   1   
22      0   1   0    0    1    0    0    0    1    1  ...    1   0   0   0   
23      1   1   1    0    0    0    0    0    1    0  ...    0   1   0   1   
24      1   1   0    0    0    0    0    0    0    0  ...    1   0   0   0   
25      0   0   0    1    1    1    1    1    1    1  ...    1   1   0   1   
26      1   1   0    1    1    1    1    1    1    1  ...    1   0   1   1   
27      0   1   1    1    1    1    1    1    0    1  ...    0   1   0   1   
28      1   1   0    0    0    0    0    0    1    1  ...    1   1   1   1   
29      1   1   1    1    1    1    1    1    1    0  ...    0   0   0   1   
...    ..  ..  ..  ...  ...  ...  ...  ...  ...  ...  ...  ...  ..  ..  ..   
10635   1   1   1    0    1    0    1    1    1    1  ...    0   1   0   1   
10636   1   1   0    0    1    0    0    0    0    0  ...    1   0   0   0   
10637   1   1   0    0    1    1    1    1    1    1  ...    1   0   0   1   
10638   1   1   1    0    0    1    1    1    0    1  ...    0   0   0   1   
10639   0   1   0    1    1    1    1    1    1    1  ...    1   0   0   1   
10640   0   0   0    1    1    1    1    1    1    1  ...    1   0   1   1   
10641   1   1   1    0    0    0    0    0    0    0  ...    0   0   1   0   
10642   0   1   0    0    1    0    1    0    1    1  ...    1   0   0   1   
10643   1   1   1    1    0    1    1    1    0    1  ...    0   0   0   0   
10644   1   0   0    1    1    1    0    1    1    1  ...    1   0   0   1   
10645   1   1   1    0    0    0    0    0    0    0  ...    0   1   0   1   
10646   0   1   0    0    1    0    1    1    1    1  ...    1   0   0   1   
10647   0   0   0    1    1    1    1    1    1    1  ...    1   0   0   0   
10648   1   1   1    0    1    0    0    0    0    0  ...    0   0   0   1   
10649   0   0   0    1    1    1    1    1    1    1  ...    1   1   1   1   
10650   0   1   0    1    1    1    1    1    1    1  ...    1   1   1   1   
10651   1   1   0    1    1    1    1    1    1    1  ...    1   0   0   1   
10652   0   1   1    1    1    0    1    1    1    1  ...    0   0   1   0   
10653   1   1   1    0    0    0    0    0    0    0  ...    0   0   0   0   
10654   1   1   1    0    0  

In [17]:
dfx_imputed.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10665 entries, 0 to 10664
Data columns (total 36 columns):
Y2     10665 non-null int64
Y3     10665 non-null int64
Y4     10665 non-null int64
C01    10665 non-null int64
C02    10665 non-null int64
C03    10665 non-null int64
C04    10665 non-null int64
C05    10665 non-null int64
C06    10665 non-null int64
C07    10665 non-null int64
C08    10665 non-null int64
C09    10665 non-null int64
C10    10665 non-null int64
C11    10665 non-null int64
C12    10665 non-null int64
C13    10665 non-null int64
C14    10665 non-null int64
C15    10665 non-null int64
C16    10665 non-null int64
C17    10665 non-null int64
C18    10665 non-null int64
C19    10665 non-null int64
C20    10665 non-null int64
C21    10665 non-null int64
C22    10665 non-null int64
C23    10665 non-null int64
C24    10665 non-null int64
X1     10665 non-null int64
X2     10665 non-null int64
X3     10665 non-null int64
X4     10665 non-null int64
X5     10665 non-null i

## Data Processing

### Attributes

In [18]:
def convert_binary_and_category(x,variable_type):
    """
    convert binary to +-1, category to one hot; remain continuous.
    """
    
    onehot_encoder = OneHotEncoder(sparse=False,categories='auto')

    # create 2 initial columns
    x_new = np.zeros((x.shape[0],2))

    for i,i_type in enumerate(variable_type):
        if i_type == 1: # binary
            unique_value = np.unique(x[:,i])
            x1 = np.array([-1. if value == unique_value[0] else 1. for value in x[:,i]])        
            x_new = np.hstack((x_new,x1[:,np.newaxis]))

        elif i_type == 2: # category
            x1 = onehot_encoder.fit_transform(x[:,i].reshape(-1,1))
            x_new = np.hstack((x_new,x1))
            
        else: # continuous      
            x_new = np.hstack((x_new,x[:,i][:,np.newaxis]))      

    # drop the 2 initial column
    x_new = x_new[:,2:]
    
    return x_new.astype(float)

In [19]:
# convert x
x = np.array(dfx_imputed)
x_new = convert_binary_and_category(x,variable_type)

print(x_new.shape)
print(x_new)

(10665, 36)
[[-1.  1. -1. ... -1.  1. -1.]
 [-1.  1.  1. ... -1.  1. -1.]
 [ 1.  1. -1. ... -1.  1. -1.]
 ...
 [ 1.  1.  1. ... -1.  1.  1.]
 [ 1. -1. -1. ... -1. -1. -1.]
 [ 1.  1. -1. ... -1.  1. -1.]]


### Target

In [20]:
y = np.array(dfy)
print(np.unique(y,return_counts=True))

# if target is already 0 and 1
y_new = y 
print(np.unique(y_new,return_counts=True))

(array([0, 1]), array([2725, 7940]))
(array([0, 1]), array([2725, 7940]))


In [21]:
# combine X and y and save to a file
xy_new = np.hstack((x_new,y_new[:,np.newaxis]))
np.savetxt('stigma_processed.dat',xy_new,fmt='%f')