In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
#from sklearn.preprocessing import Imputer

In [2]:
np.random.seed(1)

In [3]:
df = pd.read_csv("smoking.csv")
df

age  gender  A1  A2_completed_education  A3  A4    A5   A6   A7   A8  \
0      35       2   1                       2   2   1   NaN  2.0  3.0  1.0   
1      34       1   4                       3   3   1   NaN  2.0  3.0  1.0   
2      37       2   3                       3   3   1   NaN  4.0  2.0  1.0   
3      37       2   3                       3   3   1   NaN  4.0  2.0  1.0   
4      35       2   2                       3   3   3   NaN  NaN  NaN  NaN   
5      29       2   5                       3   2   1   NaN  4.0  2.0  1.0   
6      48       1   2                       3   3   1   NaN  2.0  3.0  1.0   
7      41       2   5                       3   3   1   NaN  3.0  2.0  1.0   
8      15       1   5                       1   1   1   NaN  1.0  3.0  1.0   
9      37       2   1                       3   1   1   NaN  3.0  2.0  1.0   
10     56       1   1                       3   2   4   NaN  NaN  NaN  NaN   
11     23       2   5                       2   1   2   3.0  1.0  4.0  1.0   
12     49       2   1                       3   2   4   NaN  NaN  NaN  NaN   
13     36       2   2                       2   1   2   1.0  1.0  NaN  1.0   
14     34       2   1                       3   2   1   NaN  3.0  1.0  1.0   
15     32       1   1                       2   1   4   NaN  NaN  NaN  NaN   
16     38       1   1                       2   1   4   NaN  NaN  NaN  NaN   
17     44       1   1                       2   4   1   NaN  4.0  2.0  1.0   
18     51       1   3                       3   4   3   NaN  NaN  NaN  NaN   
19     29       1   1                       3   2   1   NaN  3.0  1.0  1.0   
20     23       1   5                       2   1   4   NaN  NaN  NaN  NaN   
21     32       1   1                       3   1   4   NaN  NaN  NaN  NaN   
22     27       1   2                       3   3   4   NaN  NaN  NaN  NaN   
23     62       1   4                       3   3   3   NaN  NaN  NaN  NaN   
24     67       1   4                       2   5   3   NaN  NaN  NaN  NaN   
25     34       1   1                       3   2   1   NaN  3.0  2.0  1.0   
26     29       2   1                       3   1   1   NaN  2.0  3.0  1.0   
27     60       2   1                       1   5   3   NaN  NaN  NaN  NaN   
28     65       1   1                       1   2   4   NaN  NaN  NaN  NaN   
29     54       2   3                       2   2   4   NaN  NaN  NaN  NaN   
...   ...     ...  ..                     ...  ..  ..   ...  ...  ...  ...   
1558   61       1   2                       2   4   2   NaN  NaN  NaN  NaN   
1559   36       1   1                       3   3   4   NaN  NaN  NaN  NaN   
1560   44       2   1                       3   3   2   3.0  1.0  4.0  1.0   
1561   31       2   5                       3   3   1   NaN  4.0  2.0  1.0   
1562   35       2   2                       3   3   3   NaN  NaN  NaN  NaN   
1563   14       2   5                       1   1   1   NaN  1.0  2.0  1.0   
1564   15       1   5                       1   1   2   3.0  1.0  4.0  1.0   
1565   61       2   1                       1   2   4   NaN  NaN  NaN  NaN   
1566   51       2   1                       2   4   1  99.0  4.0  1.0  1.0   
1567   34       1   3                       3   3   1   NaN  2.0  2.0  1.0   
1568   37       1   5                       2   1   4   NaN  NaN  NaN  NaN   
1569   37       1   2                       3   1   1   NaN  3.0  2.0  1.0   
1570   44       2   1                       1   3   1   NaN  4.0  2.0  1.0   
1571   28       1   4                       3   2   4   NaN  NaN  NaN  NaN   
1572   29       1   2                       3   2   2   5.0  1.0  4.0  1.0   
1573   47       2   1                       1   2   1   NaN  3.0  3.0  1.0   
1574   70       1   4                       1   2   4   NaN  NaN  NaN  NaN   
1575   27       1   1                       2   2   4   NaN  NaN  NaN  NaN   
1576   57       2   1                       1   4   1   NaN  3.0  2.0  1.0   
1577   53       1   1       

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1588 entries, 0 to 1587
Columns: 119 entries, age to a4_smoking_status
dtypes: float64(49), int64(70)
memory usage: 1.4 MB


In [5]:
# replace empty by nan
df = df.replace(r'^\s+$', np.nan, regex=True)
df = df.replace('99',np.nan,regex=True)
df = df.replace(99,np.nan,regex=True)
df

age  gender  A1  A2_completed_education  A3  A4   A5   A6   A7   A8  \
0      35       2   1                       2   2   1  NaN  2.0  3.0  1.0   
1      34       1   4                       3   3   1  NaN  2.0  3.0  1.0   
2      37       2   3                       3   3   1  NaN  4.0  2.0  1.0   
3      37       2   3                       3   3   1  NaN  4.0  2.0  1.0   
4      35       2   2                       3   3   3  NaN  NaN  NaN  NaN   
5      29       2   5                       3   2   1  NaN  4.0  2.0  1.0   
6      48       1   2                       3   3   1  NaN  2.0  3.0  1.0   
7      41       2   5                       3   3   1  NaN  3.0  2.0  1.0   
8      15       1   5                       1   1   1  NaN  1.0  3.0  1.0   
9      37       2   1                       3   1   1  NaN  3.0  2.0  1.0   
10     56       1   1                       3   2   4  NaN  NaN  NaN  NaN   
11     23       2   5                       2   1   2  3.0  1.0  4.0  1.0   
12     49       2   1                       3   2   4  NaN  NaN  NaN  NaN   
13     36       2   2                       2   1   2  1.0  1.0  NaN  1.0   
14     34       2   1                       3   2   1  NaN  3.0  1.0  1.0   
15     32       1   1                       2   1   4  NaN  NaN  NaN  NaN   
16     38       1   1                       2   1   4  NaN  NaN  NaN  NaN   
17     44       1   1                       2   4   1  NaN  4.0  2.0  1.0   
18     51       1   3                       3   4   3  NaN  NaN  NaN  NaN   
19     29       1   1                       3   2   1  NaN  3.0  1.0  1.0   
20     23       1   5                       2   1   4  NaN  NaN  NaN  NaN   
21     32       1   1                       3   1   4  NaN  NaN  NaN  NaN   
22     27       1   2                       3   3   4  NaN  NaN  NaN  NaN   
23     62       1   4                       3   3   3  NaN  NaN  NaN  NaN   
24     67       1   4                       2   5   3  NaN  NaN  NaN  NaN   
25     34       1   1                       3   2   1  NaN  3.0  2.0  1.0   
26     29       2   1                       3   1   1  NaN  2.0  3.0  1.0   
27     60       2   1                       1   5   3  NaN  NaN  NaN  NaN   
28     65       1   1                       1   2   4  NaN  NaN  NaN  NaN   
29     54       2   3                       2   2   4  NaN  NaN  NaN  NaN   
...   ...     ...  ..                     ...  ..  ..  ...  ...  ...  ...   
1558   61       1   2                       2   4   2  NaN  NaN  NaN  NaN   
1559   36       1   1                       3   3   4  NaN  NaN  NaN  NaN   
1560   44       2   1                       3   3   2  3.0  1.0  4.0  1.0   
1561   31       2   5                       3   3   1  NaN  4.0  2.0  1.0   
1562   35       2   2                       3   3   3  NaN  NaN  NaN  NaN   
1563   14       2   5                       1   1   1  NaN  1.0  2.0  1.0   
1564   15       1   5                       1   1   2  3.0  1.0  4.0  1.0   
1565   61       2   1                       1   2   4  NaN  NaN  NaN  NaN   
1566   51       2   1                       2   4   1  NaN  4.0  1.0  1.0   
1567   34       1   3                       3   3   1  NaN  2.0  2.0  1.0   
1568   37       1   5                       2   1   4  NaN  NaN  NaN  NaN   
1569   37       1   2                       3   1   1  NaN  3.0  2.0  1.0   
1570   44       2   1                       1   3   1  NaN  4.0  2.0  1.0   
1571   28       1   4                       3   2   4  NaN  NaN  NaN  NaN   
1572   29       1   2                       3   2   2  5.0  1.0  4.0  1.0   
1573   47       2   1                       1   2   1  NaN  3.0  3.0  1.0   
1574   70       1   4                       1   2   4  NaN  NaN  NaN  NaN   
1575   27       1   1                       2   2   4  NaN  NaN  NaN  NaN   
1576   57       2   1                       1   4   1  NaN  3.0  2.0  1.0   
1577   53       1   1                       3   2   4  NaN  NaN  NaN  NaN   
15

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1588 entries, 0 to 1587
Columns: 119 entries, age to a4_smoking_status
dtypes: float64(84), int64(35)
memory usage: 1.4 MB


In [7]:
df = df.replace('\t','',regex=True)
df = df.replace(' ','',regex=True)
df = df.replace('\?','np.nan',regex=True)

## Data Cleaning

In [8]:
# Remove rows where taget are missing
missing_row = df['healthstatus3'].isnull()
print('Number of rows where target are missing:')
print(sum(missing_row))

df = df[~missing_row]
df

Number of rows where target are missing:
0


age  gender  A1  A2_completed_education  A3  A4   A5   A6   A7   A8  \
0      35       2   1                       2   2   1  NaN  2.0  3.0  1.0   
1      34       1   4                       3   3   1  NaN  2.0  3.0  1.0   
2      37       2   3                       3   3   1  NaN  4.0  2.0  1.0   
3      37       2   3                       3   3   1  NaN  4.0  2.0  1.0   
4      35       2   2                       3   3   3  NaN  NaN  NaN  NaN   
5      29       2   5                       3   2   1  NaN  4.0  2.0  1.0   
6      48       1   2                       3   3   1  NaN  2.0  3.0  1.0   
7      41       2   5                       3   3   1  NaN  3.0  2.0  1.0   
8      15       1   5                       1   1   1  NaN  1.0  3.0  1.0   
9      37       2   1                       3   1   1  NaN  3.0  2.0  1.0   
10     56       1   1                       3   2   4  NaN  NaN  NaN  NaN   
11     23       2   5                       2   1   2  3.0  1.0  4.0  1.0   
12     49       2   1                       3   2   4  NaN  NaN  NaN  NaN   
13     36       2   2                       2   1   2  1.0  1.0  NaN  1.0   
14     34       2   1                       3   2   1  NaN  3.0  1.0  1.0   
15     32       1   1                       2   1   4  NaN  NaN  NaN  NaN   
16     38       1   1                       2   1   4  NaN  NaN  NaN  NaN   
17     44       1   1                       2   4   1  NaN  4.0  2.0  1.0   
18     51       1   3                       3   4   3  NaN  NaN  NaN  NaN   
19     29       1   1                       3   2   1  NaN  3.0  1.0  1.0   
20     23       1   5                       2   1   4  NaN  NaN  NaN  NaN   
21     32       1   1                       3   1   4  NaN  NaN  NaN  NaN   
22     27       1   2                       3   3   4  NaN  NaN  NaN  NaN   
23     62       1   4                       3   3   3  NaN  NaN  NaN  NaN   
24     67       1   4                       2   5   3  NaN  NaN  NaN  NaN   
25     34       1   1                       3   2   1  NaN  3.0  2.0  1.0   
26     29       2   1                       3   1   1  NaN  2.0  3.0  1.0   
27     60       2   1                       1   5   3  NaN  NaN  NaN  NaN   
28     65       1   1                       1   2   4  NaN  NaN  NaN  NaN   
29     54       2   3                       2   2   4  NaN  NaN  NaN  NaN   
...   ...     ...  ..                     ...  ..  ..  ...  ...  ...  ...   
1558   61       1   2                       2   4   2  NaN  NaN  NaN  NaN   
1559   36       1   1                       3   3   4  NaN  NaN  NaN  NaN   
1560   44       2   1                       3   3   2  3.0  1.0  4.0  1.0   
1561   31       2   5                       3   3   1  NaN  4.0  2.0  1.0   
1562   35       2   2                       3   3   3  NaN  NaN  NaN  NaN   
1563   14       2   5                       1   1   1  NaN  1.0  2.0  1.0   
1564   15       1   5                       1   1   2  3.0  1.0  4.0  1.0   
1565   61       2   1                       1   2   4  NaN  NaN  NaN  NaN   
1566   51       2   1                       2   4   1  NaN  4.0  1.0  1.0   
1567   34       1   3                       3   3   1  NaN  2.0  2.0  1.0   
1568   37       1   5                       2   1   4  NaN  NaN  NaN  NaN   
1569   37       1   2                       3   1   1  NaN  3.0  2.0  1.0   
1570   44       2   1                       1   3   1  NaN  4.0  2.0  1.0   
1571   28       1   4                       3   2   4  NaN  NaN  NaN  NaN   
1572   29       1   2                       3   2   2  5.0  1.0  4.0  1.0   
1573   47       2   1                       1   2   1  NaN  3.0  3.0  1.0   
1574   70       1   4                       1   2   4  NaN  NaN  NaN  NaN   
1575   27       1   1                       2   2   4  NaN  NaN  NaN  NaN   
1576   57       2   1                       1   4   1  NaN  3.0  2.0  1.0   
1577   53       1   1                       3   2   4  NaN  NaN  NaN  NaN   
15

We determine and drop the variables with excessive missing values from the dataset.

In [9]:
def remove_bad_columns(df,bad_column_threshold):
    # find bad columns having too many missing values
    n_null = np.array(df.isnull().sum(axis=0))
    bad_col = np.array([]).astype(int)
    for i in range(len(n_null)):
        if n_null[i] >= bad_column_threshold:
            bad_col = np.append(bad_col,i)

    #print(bad_col)
    print('number of bad columns:',len(bad_col))

    # delete bad columns
    df = df.drop(df.columns[bad_col],axis=1)
    #df.info()
    return df   

In [10]:
df = remove_bad_columns(df,200)
df

number of bad columns: 23


age  gender  A1  A2_completed_education  A3  A4   A9  A16  A17  A18  \
0      35       2   1                       2   2   1  6.0  0.0  0.0    0   
1      34       1   4                       3   3   1  6.0  1.0  1.0    1   
2      37       2   3                       3   3   1  6.0  1.0  1.0    0   
3      37       2   3                       3   3   1  6.0  1.0  1.0    0   
4      35       2   2                       3   3   3  6.0  1.0  1.0    0   
5      29       2   5                       3   2   1  2.0  1.0  1.0    0   
6      48       1   2                       3   3   1  6.0  1.0  1.0    1   
7      41       2   5                       3   3   1  6.0  1.0  1.0    0   
8      15       1   5                       1   1   1  6.0  1.0  1.0    1   
9      37       2   1                       3   1   1  6.0  1.0  1.0    0   
10     56       1   1                       3   2   4  6.0  1.0  1.0    1   
11     23       2   5                       2   1   2  6.0  1.0  1.0    1   
12     49       2   1                       3   2   4  6.0  1.0  1.0    1   
13     36       2   2                       2   1   2  6.0  0.0  0.0    0   
14     34       2   1                       3   2   1  2.0  1.0  1.0    1   
15     32       1   1                       2   1   4  6.0  1.0  1.0    1   
16     38       1   1                       2   1   4  6.0  1.0  1.0    1   
17     44       1   1                       2   4   1  6.0  1.0  1.0    0   
18     51       1   3                       3   4   3  6.0  1.0  1.0    1   
19     29       1   1                       3   2   1  6.0  1.0  1.0    1   
20     23       1   5                       2   1   4  6.0  1.0  1.0    1   
21     32       1   1                       3   1   4  6.0  1.0  1.0    1   
22     27       1   2                       3   3   4  6.0  1.0  1.0    1   
23     62       1   4                       3   3   3  6.0  1.0  1.0    1   
24     67       1   4                       2   5   3  6.0  1.0  1.0    1   
25     34       1   1                       3   2   1  6.0  1.0  1.0    0   
26     29       2   1                       3   1   1  6.0  0.0  0.0    0   
27     60       2   1                       1   5   3  6.0  1.0  1.0    1   
28     65       1   1                       1   2   4  6.0  1.0  1.0    1   
29     54       2   3                       2   2   4  6.0  1.0  1.0    1   
...   ...     ...  ..                     ...  ..  ..  ...  ...  ...  ...   
1558   61       1   2                       2   4   2  6.0  0.0  0.0    0   
1559   36       1   1                       3   3   4  6.0  0.0  0.0    1   
1560   44       2   1                       3   3   2  6.0  1.0  1.0    0   
1561   31       2   5                       3   3   1  3.0  1.0  1.0    0   
1562   35       2   2                       3   3   3  6.0  1.0  1.0    0   
1563   14       2   5                       1   1   1  6.0  0.0  0.0    0   
1564   15       1   5                       1   1   2  6.0  0.0  0.0    0   
1565   61       2   1                       1   2   4  6.0  1.0  1.0    1   
1566   51       2   1                       2   4   1  6.0  1.0  0.0    1   
1567   34       1   3                       3   3   1  6.0  1.0  1.0    1   
1568   37       1   5                       2   1   4  NaN  1.0  1.0    1   
1569   37       1   2                       3   1   1  6.0  0.0  0.0    0   
1570   44       2   1                       1   3   1  6.0  1.0  1.0    1   
1571   28       1   4                       3   2   4  6.0  1.0  1.0    1   
1572   29       1   2                       3   2   2  6.0  1.0  1.0    0   
1573   47       2   1                       1   2   1  6.0  0.0  0.0    0   
1574   70       1   4                       1   2   4  6.0  1.0  1.0    1   
1575   27       1   1                       2   2   4  6.0  1.0  1.0    1   
1576   57       2   1                       1   4   1  6.0  1.0  1.0    1   
1577   53       1   1                       3   2   4  6.0  1.0  1.0    1   
15

We find bad rows which contain too many missing values, then remove them.

In [11]:
def remove_bad_rows(df,bad_row_threshold):   
    # find bad rows having too many missing values
    n_null = np.array(df.isnull().sum(axis=1))
    bad_row = np.array([]).astype(int)
    for t in range(len(n_null)):
        if n_null[t] >= bad_row_threshold:
            bad_row = np.append(bad_row,t)

    #print(bad_row)
    print('number of bad rows:',len(bad_row))

    # delete bad rows
    df = df.drop(bad_row)
    #df.info()
    return df

In [12]:
df = remove_bad_rows(df,10)
df

number of bad rows: 14


age  gender  A1  A2_completed_education  A3  A4   A9  A16  A17  A18  \
0      35       2   1                       2   2   1  6.0  0.0  0.0    0   
1      34       1   4                       3   3   1  6.0  1.0  1.0    1   
2      37       2   3                       3   3   1  6.0  1.0  1.0    0   
3      37       2   3                       3   3   1  6.0  1.0  1.0    0   
4      35       2   2                       3   3   3  6.0  1.0  1.0    0   
5      29       2   5                       3   2   1  2.0  1.0  1.0    0   
6      48       1   2                       3   3   1  6.0  1.0  1.0    1   
7      41       2   5                       3   3   1  6.0  1.0  1.0    0   
8      15       1   5                       1   1   1  6.0  1.0  1.0    1   
9      37       2   1                       3   1   1  6.0  1.0  1.0    0   
10     56       1   1                       3   2   4  6.0  1.0  1.0    1   
11     23       2   5                       2   1   2  6.0  1.0  1.0    1   
12     49       2   1                       3   2   4  6.0  1.0  1.0    1   
13     36       2   2                       2   1   2  6.0  0.0  0.0    0   
14     34       2   1                       3   2   1  2.0  1.0  1.0    1   
15     32       1   1                       2   1   4  6.0  1.0  1.0    1   
16     38       1   1                       2   1   4  6.0  1.0  1.0    1   
17     44       1   1                       2   4   1  6.0  1.0  1.0    0   
18     51       1   3                       3   4   3  6.0  1.0  1.0    1   
19     29       1   1                       3   2   1  6.0  1.0  1.0    1   
20     23       1   5                       2   1   4  6.0  1.0  1.0    1   
21     32       1   1                       3   1   4  6.0  1.0  1.0    1   
22     27       1   2                       3   3   4  6.0  1.0  1.0    1   
23     62       1   4                       3   3   3  6.0  1.0  1.0    1   
24     67       1   4                       2   5   3  6.0  1.0  1.0    1   
25     34       1   1                       3   2   1  6.0  1.0  1.0    0   
26     29       2   1                       3   1   1  6.0  0.0  0.0    0   
27     60       2   1                       1   5   3  6.0  1.0  1.0    1   
28     65       1   1                       1   2   4  6.0  1.0  1.0    1   
29     54       2   3                       2   2   4  6.0  1.0  1.0    1   
...   ...     ...  ..                     ...  ..  ..  ...  ...  ...  ...   
1544   17       2   5                       1   1   1  6.0  0.0  0.0    0   
1545   23       1   5                       2   1   4  6.0  1.0  1.0    1   
1546   36       1   1                       2   2   4  6.0  1.0  1.0    1   
1547   18       2   5                       2   1   4  6.0  1.0  1.0    1   
1548   32       2   5                       2   1   4  6.0  1.0  1.0    1   
1549   24       1   5                       3   1   1  6.0  1.0  0.0    0   
1550   32       1   1                       3   2   1  6.0  0.0  0.0    0   
1551   23       2   5                       2   1   1  6.0  0.0  0.0    0   
1552   23       2   5                       2   2   2  6.0  1.0  1.0    0   
1553   21       1   5                       3   2   1  6.0  1.0  1.0    1   
1554   61       2   4                       2   4   1  6.0  1.0  0.0    0   
1555   61       2   3                       2   4   1  6.0  1.0  0.0    0   
1556   38       2   3                       1   1   1  2.0  0.0  1.0    0   
1557   18       1   5                       1   1   2  6.0  0.0  0.0    0   
1558   61       1   2                       2   4   2  6.0  0.0  0.0    0   
1559   36       1   1                       3   3   4  6.0  0.0  0.0    1   
1560   44       2   1                       3   3   2  6.0  1.0  1.0    0   
1561   31       2   5                       3   3   1  3.0  1.0  1.0    0   
1562   35       2   2                       3   3   3  6.0  1.0  1.0    0   
1563   14       2   5                       1   1   1  6.0  0.0  0.0    0   
15

For convenience, we separate independents `X` and dependent `y` from the data.

In [13]:
dfx = df.drop('healthstatus3',axis=1)
dfy = df['healthstatus3']

In [14]:
# number of uniques of each column (excluding NaN)
nu = np.array([len(pd.unique(dfx[col].dropna())) for col in dfx.columns])
print('number of uniques of each variable:')
print(nu)

number of uniques of each variable:
[  58    2    5    3    5    4    5    2    2    2    2    2    2    3
    3    3    3    5    2    2    2    3    2    2    2    2    2    2
    7    8    2    2    2    2    2    2    2    3    3    3    3    2
 1565   10    3    2    2    2    5    2    3    7    3    2    2    2
    2    2    2    2    2    2    4    2    2    2    2    2    2    2
    2    9    2    9    2    2    2    2    2    2    2    2    2    2
    2    2    2    2    2    2    2    2    2    3    4]


In [15]:
def define_variable_type(df,nu):
    i_binary = [] ; i_category = [] ; i_continuous = []
    for i in range(len(nu)):
        if nu[i] == 2: # binary 
            i_binary.append(i)
        elif nu[i] < 5: # !!!! NOTE: this is not always correct, depending on data
            i_category.append(i)
        else:
            i_continuous.append(i)

    print('i_binary:',i_binary)
    print('i_category:',i_category)   
    #i_binary, i_category, i_continuous
    
    variable_type  = np.ones(len(nu))  # binary
    variable_type[i_category] = 2   # categorical
    variable_type[i_continuous] = 3 # continuous

    return variable_type #,i_binary,i_category,i_continuous

In [16]:
variable_type = define_variable_type(dfx,nu)
print('variable type:',variable_type)

i_binary: [1, 7, 8, 9, 10, 11, 12, 18, 19, 20, 22, 23, 24, 25, 26, 27, 30, 31, 32, 33, 34, 35, 36, 41, 45, 46, 47, 49, 53, 54, 55, 56, 57, 58, 59, 60, 61, 63, 64, 65, 66, 67, 68, 69, 70, 72, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92]
i_category: [3, 5, 13, 14, 15, 16, 21, 37, 38, 39, 40, 44, 50, 52, 62, 93, 94]
variable type: [3. 1. 3. 2. 3. 2. 3. 1. 1. 1. 1. 1. 1. 2. 2. 2. 2. 3. 1. 1. 1. 2. 1. 1.
 1. 1. 1. 1. 3. 3. 1. 1. 1. 1. 1. 1. 1. 2. 2. 2. 2. 1. 3. 3. 2. 1. 1. 1.
 3. 1. 2. 3. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 3.
 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 2.]


In [17]:
def impute_missing(df,variable_type):
    # impute binary and categorical variables by the most frequency (in each column)
    # continuous variable by median
    # input: df: pandas data frame, variable_type: list
    # output: df2: pandas data frame
    df2 = df.copy()
    for i,col in enumerate(df.columns):
        if variable_type[i] < 3: # binary or caterogy
            df2[col] = df[col].fillna(df[col].mode().iloc[0])
        else: # continuous
            df2[col] = df[col].fillna(df[col].median())    
    return df2       

In [18]:
dfx_imputed = impute_missing(dfx,variable_type)
dfx_imputed

age  gender  A1  A2_completed_education  A3  A4   A9  A16  A17  A18  \
0      35       2   1                       2   2   1  6.0  0.0  0.0    0   
1      34       1   4                       3   3   1  6.0  1.0  1.0    1   
2      37       2   3                       3   3   1  6.0  1.0  1.0    0   
3      37       2   3                       3   3   1  6.0  1.0  1.0    0   
4      35       2   2                       3   3   3  6.0  1.0  1.0    0   
5      29       2   5                       3   2   1  2.0  1.0  1.0    0   
6      48       1   2                       3   3   1  6.0  1.0  1.0    1   
7      41       2   5                       3   3   1  6.0  1.0  1.0    0   
8      15       1   5                       1   1   1  6.0  1.0  1.0    1   
9      37       2   1                       3   1   1  6.0  1.0  1.0    0   
10     56       1   1                       3   2   4  6.0  1.0  1.0    1   
11     23       2   5                       2   1   2  6.0  1.0  1.0    1   
12     49       2   1                       3   2   4  6.0  1.0  1.0    1   
13     36       2   2                       2   1   2  6.0  0.0  0.0    0   
14     34       2   1                       3   2   1  2.0  1.0  1.0    1   
15     32       1   1                       2   1   4  6.0  1.0  1.0    1   
16     38       1   1                       2   1   4  6.0  1.0  1.0    1   
17     44       1   1                       2   4   1  6.0  1.0  1.0    0   
18     51       1   3                       3   4   3  6.0  1.0  1.0    1   
19     29       1   1                       3   2   1  6.0  1.0  1.0    1   
20     23       1   5                       2   1   4  6.0  1.0  1.0    1   
21     32       1   1                       3   1   4  6.0  1.0  1.0    1   
22     27       1   2                       3   3   4  6.0  1.0  1.0    1   
23     62       1   4                       3   3   3  6.0  1.0  1.0    1   
24     67       1   4                       2   5   3  6.0  1.0  1.0    1   
25     34       1   1                       3   2   1  6.0  1.0  1.0    0   
26     29       2   1                       3   1   1  6.0  0.0  0.0    0   
27     60       2   1                       1   5   3  6.0  1.0  1.0    1   
28     65       1   1                       1   2   4  6.0  1.0  1.0    1   
29     54       2   3                       2   2   4  6.0  1.0  1.0    1   
...   ...     ...  ..                     ...  ..  ..  ...  ...  ...  ...   
1544   17       2   5                       1   1   1  6.0  0.0  0.0    0   
1545   23       1   5                       2   1   4  6.0  1.0  1.0    1   
1546   36       1   1                       2   2   4  6.0  1.0  1.0    1   
1547   18       2   5                       2   1   4  6.0  1.0  1.0    1   
1548   32       2   5                       2   1   4  6.0  1.0  1.0    1   
1549   24       1   5                       3   1   1  6.0  1.0  0.0    0   
1550   32       1   1                       3   2   1  6.0  0.0  0.0    0   
1551   23       2   5                       2   1   1  6.0  0.0  0.0    0   
1552   23       2   5                       2   2   2  6.0  1.0  1.0    0   
1553   21       1   5                       3   2   1  6.0  1.0  1.0    1   
1554   61       2   4                       2   4   1  6.0  1.0  0.0    0   
1555   61       2   3                       2   4   1  6.0  1.0  0.0    0   
1556   38       2   3                       1   1   1  2.0  0.0  1.0    0   
1557   18       1   5                       1   1   2  6.0  0.0  0.0    0   
1558   61       1   2                       2   4   2  6.0  0.0  0.0    0   
1559   36       1   1                       3   3   4  6.0  0.0  0.0    1   
1560   44       2   1                       3   3   2  6.0  1.0  1.0    0   
1561   31       2   5                       3   3   1  3.0  1.0  1.0    0   
1562   35       2   2                       3   3   3  6.0  1.0  1.0    0   
1563   14       2   5                       1   1   1  6.0  0.0  0.0    0   
15

In [19]:
dfx_imputed.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1574 entries, 0 to 1573
Data columns (total 95 columns):
age                             1574 non-null int64
gender                          1574 non-null int64
A1                              1574 non-null int64
A2_completed_education          1574 non-null int64
A3                              1574 non-null int64
A4                              1574 non-null int64
A9                              1574 non-null float64
A16                             1574 non-null float64
A17                             1574 non-null float64
A18                             1574 non-null int64
A19                             1574 non-null int64
A20                             1574 non-null int64
A21                             1574 non-null float64
A22                             1574 non-null float64
A23                             1574 non-null int64
A24                             1574 non-null int64
A25                             1574 non-null int64

## Data Processing

### Attributes

In [20]:
def convert_binary_and_category(x,variable_type):
    """
    convert binary to +-1, category to one hot; remain continuous.
    """
    
    onehot_encoder = OneHotEncoder(sparse=False,categories='auto')

    # create 2 initial columns
    x_new = np.zeros((x.shape[0],2))

    for i,i_type in enumerate(variable_type):
        if i_type == 1: # binary
            unique_value = np.unique(x[:,i])
            x1 = np.array([-1. if value == unique_value[0] else 1. for value in x[:,i]])        
            x_new = np.hstack((x_new,x1[:,np.newaxis]))

        elif i_type == 2: # category
            x1 = onehot_encoder.fit_transform(x[:,i].reshape(-1,1))
            x_new = np.hstack((x_new,x1))
            
        else: # continuous      
            x_new = np.hstack((x_new,x[:,i][:,np.newaxis]))      

    # drop the 2 initial column
    x_new = x_new[:,2:]
    
    return x_new.astype(float)

In [21]:
# convert x
x = np.array(dfx_imputed)
x_new = convert_binary_and_category(x,variable_type)

print(x_new.shape)
print(x_new)

(1574, 132)
[[35.  1.  1. ...  0.  0.  0.]
 [34. -1.  4. ...  0.  0.  0.]
 [37.  1.  3. ...  0.  0.  0.]
 ...
 [28. -1.  4. ...  0.  0.  1.]
 [29. -1.  2. ...  1.  0.  0.]
 [47.  1.  1. ...  0.  0.  0.]]


### Target

In [22]:
y = np.array(dfy)
print(np.unique(y,return_counts=True))

# if target is already 0 and 1
y_new = y  
print(np.unique(y_new,return_counts=True))

(array([0, 1]), array([852, 722]))
(array([0, 1]), array([852, 722]))


In [23]:
# combine X and y and save to a file
xy_new = np.hstack((x_new,y_new[:,np.newaxis]))
np.savetxt('smoking_processed.dat',xy_new,fmt='%f')