In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
#from sklearn.preprocessing import Imputer

In [2]:
np.random.seed(1)

In [3]:
df = pd.read_csv("anemia.csv")
df

ID  center        age  sex        BMI  type2  duration  HTN  HLP  \
0    M003       1  56.065753    1  26.297578      1       1.0    0    0   
1    M008       1  55.339726    1  33.208550      1       0.5    1    1   
2    M009       1  75.786301    0  27.688778      1       6.0    1    0   
3    M015       1  43.213699    0        NaN      1       1.0    0    0   
4    M033       1  60.060274    0  26.927438      1       4.0    1    1   
5    M035       1  49.194521    0  20.863177      1       1.0    1    1   
6    M037       1  83.849315    0  21.875000      1      24.0    1    0   
7    M041       1  44.194521    0  26.927438      1       1.0    1    0   
8    M043       1  57.712329    0  36.810592      1      24.0    1    0   
9    M044       1  76.471233    0  25.160698      1       1.0    1    0   
10   M045       1  85.693151    1  30.116213      1       4.0    1    1   
11   M046       1  70.523288    1  43.426532      1       5.0    1    0   
12   M051       1  61.334247    1  35.896340      1       0.5    1    0   
13   M055       1  66.487671    1  24.538965      1       2.0    0    0   
14   M056       1  54.172603    1  37.460978      1       5.0    1    1   
15   M060       1  78.210959    0  21.270630      1       4.0    1    0   
16   M068       1  60.668493    0  32.046146      1       9.0    1    1   
17   M071       1  66.487671    0  29.372397      1       0.5    1    1   
18   M073       1  57.780822    0  39.736121      1       8.0    1    1   
19   M074       1  73.328767    0  32.769395      1      12.0    1    1   
20   M077       1  68.246575    0  28.928337      1      20.0    0    0   
21   M080       1  51.863014    1  36.204986      1       4.0    1    1   
22   M082       1  67.317808    1  32.911223      1       6.0    0    1   
23   M083       1  58.641096    0  28.378215      1      22.0    0    0   
24   M084       1  46.224658    0  43.359375      1       5.0    1    0   
25   M086       1  64.191781    1  30.137993      1      15.0    1    0   
26   M090       1  67.298630    0  34.894399      1      15.0    1    0   
27   M094       1  54.134247    1  28.216134      1       4.0    1    0   
28   M095       1  55.279452    0  27.767098      1       2.0    0    0   
29   M103       1  59.038356    1  30.835753      1      19.0    1    0   
..    ...     ...        ...  ...        ...    ...       ...  ...  ...   
219  M197       1  62.167123    1  29.462280      1      20.0    1    0   
220  M212       1  71.208219    1  25.794163      1       7.0    1    1   
221  M244       4  70.808219    0  35.916121      1      10.0    1    1   
222  M190       1  61.791781    0  28.387441      1      28.0    1    1   
223  M149       2  75.904110    1  28.400548      1      20.0    1    1   
224  M191       1  74.621918    1  22.002551      1       9.0    1    0   
225  M209       1  78.569863    1  26.464394      1      23.0    1    1   
226  M147       2  66.695890    1  27.922368      1      20.0    1    1   
227  M155       2  71.794521    1  27.335640      1       NaN    1    1   
228  M141       1  78.756164    1  26.928180      1      31.0    1    0   
229  M216       1  66.695890    1  29.420408      1      12.0    0    1   
230  M018       1  58.997260    1  30.056811      1      40.0    1    1   
231  M126       1  64.972603    0  31.265812      1      27.0    1    1   
232  M246       4  44.087671    1  25.099502      1       4.0    1    0   
233  M005       1  57.345205    1  35.019925      1      10.0    1    1   
234  M265       1  45.884932    1  27.758490      0      43.0    1    1   
235  M194       1  53.219178    0  27.239224      1      13.0    1    1   
236  M252       4  75.230137    1  26.775510      1      12.0    1    0   
237  M210       1  71.386301    1  31.441690      1      25.0    1    0   
238  M154       2  58.142466    0  30.102119      1       NaN    1    0   
239  M150       2  66.509589    1  27.565193      1      26.0    1    1   
240  M151       2  76.632877    

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 249 entries, 0 to 248
Data columns (total 43 columns):
ID                  249 non-null object
center              249 non-null int64
age                 249 non-null float64
sex                 249 non-null int64
BMI                 246 non-null float64
type2               249 non-null int64
duration            240 non-null float64
HTN                 249 non-null int64
HLP                 249 non-null int64
vascinc             249 non-null int64
ACE                 248 non-null float64
ARB                 248 non-null float64
statin              248 non-null float64
hb                  240 non-null float64
CRP                 232 non-null float64
alb                 235 non-null float64
HbA1c               238 non-null float64
ferritin            235 non-null float64
EPO                 242 non-null float64
chol                230 non-null float64
LDL                 228 non-null float64
HDL                 229 non-null float64
hepcid

In [5]:
# replace empty by nan
df = df.replace(r'^\s+$', np.nan, regex=True)
df

ID  center        age  sex        BMI  type2  duration  HTN  HLP  \
0    M003       1  56.065753    1  26.297578      1       1.0    0    0   
1    M008       1  55.339726    1  33.208550      1       0.5    1    1   
2    M009       1  75.786301    0  27.688778      1       6.0    1    0   
3    M015       1  43.213699    0        NaN      1       1.0    0    0   
4    M033       1  60.060274    0  26.927438      1       4.0    1    1   
5    M035       1  49.194521    0  20.863177      1       1.0    1    1   
6    M037       1  83.849315    0  21.875000      1      24.0    1    0   
7    M041       1  44.194521    0  26.927438      1       1.0    1    0   
8    M043       1  57.712329    0  36.810592      1      24.0    1    0   
9    M044       1  76.471233    0  25.160698      1       1.0    1    0   
10   M045       1  85.693151    1  30.116213      1       4.0    1    1   
11   M046       1  70.523288    1  43.426532      1       5.0    1    0   
12   M051       1  61.334247    1  35.896340      1       0.5    1    0   
13   M055       1  66.487671    1  24.538965      1       2.0    0    0   
14   M056       1  54.172603    1  37.460978      1       5.0    1    1   
15   M060       1  78.210959    0  21.270630      1       4.0    1    0   
16   M068       1  60.668493    0  32.046146      1       9.0    1    1   
17   M071       1  66.487671    0  29.372397      1       0.5    1    1   
18   M073       1  57.780822    0  39.736121      1       8.0    1    1   
19   M074       1  73.328767    0  32.769395      1      12.0    1    1   
20   M077       1  68.246575    0  28.928337      1      20.0    0    0   
21   M080       1  51.863014    1  36.204986      1       4.0    1    1   
22   M082       1  67.317808    1  32.911223      1       6.0    0    1   
23   M083       1  58.641096    0  28.378215      1      22.0    0    0   
24   M084       1  46.224658    0  43.359375      1       5.0    1    0   
25   M086       1  64.191781    1  30.137993      1      15.0    1    0   
26   M090       1  67.298630    0  34.894399      1      15.0    1    0   
27   M094       1  54.134247    1  28.216134      1       4.0    1    0   
28   M095       1  55.279452    0  27.767098      1       2.0    0    0   
29   M103       1  59.038356    1  30.835753      1      19.0    1    0   
..    ...     ...        ...  ...        ...    ...       ...  ...  ...   
219  M197       1  62.167123    1  29.462280      1      20.0    1    0   
220  M212       1  71.208219    1  25.794163      1       7.0    1    1   
221  M244       4  70.808219    0  35.916121      1      10.0    1    1   
222  M190       1  61.791781    0  28.387441      1      28.0    1    1   
223  M149       2  75.904110    1  28.400548      1      20.0    1    1   
224  M191       1  74.621918    1  22.002551      1       9.0    1    0   
225  M209       1  78.569863    1  26.464394      1      23.0    1    1   
226  M147       2  66.695890    1  27.922368      1      20.0    1    1   
227  M155       2  71.794521    1  27.335640      1       NaN    1    1   
228  M141       1  78.756164    1  26.928180      1      31.0    1    0   
229  M216       1  66.695890    1  29.420408      1      12.0    0    1   
230  M018       1  58.997260    1  30.056811      1      40.0    1    1   
231  M126       1  64.972603    0  31.265812      1      27.0    1    1   
232  M246       4  44.087671    1  25.099502      1       4.0    1    0   
233  M005       1  57.345205    1  35.019925      1      10.0    1    1   
234  M265       1  45.884932    1  27.758490      0      43.0    1    1   
235  M194       1  53.219178    0  27.239224      1      13.0    1    1   
236  M252       4  75.230137    1  26.775510      1      12.0    1    0   
237  M210       1  71.386301    1  31.441690      1      25.0    1    0   
238  M154       2  58.142466    0  30.102119      1       NaN    1    0   
239  M150       2  66.509589    1  27.565193      1      26.0    1    1   
240  M151       2  76.632877    

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 249 entries, 0 to 248
Data columns (total 43 columns):
ID                  249 non-null object
center              249 non-null int64
age                 249 non-null float64
sex                 249 non-null int64
BMI                 246 non-null float64
type2               249 non-null int64
duration            240 non-null float64
HTN                 249 non-null int64
HLP                 249 non-null int64
vascinc             249 non-null int64
ACE                 248 non-null float64
ARB                 248 non-null float64
statin              248 non-null float64
hb                  240 non-null float64
CRP                 232 non-null float64
alb                 235 non-null float64
HbA1c               238 non-null float64
ferritin            235 non-null float64
EPO                 242 non-null float64
chol                230 non-null float64
LDL                 228 non-null float64
HDL                 229 non-null float64
hepcid

In [7]:
df = df.replace('\t','',regex=True)
df = df.replace(' ','',regex=True)
df = df.replace('\?','np.nan',regex=True)
df = df.replace('\.',np.nan,regex=True)

## Data Cleaning

In [8]:
# Drop the column `ID` as it is unrelated to the dependent variable
df = df.drop(['ID','cause_of_death'],axis=1)
df

center        age  sex        BMI  type2  duration  HTN  HLP  vascinc  \
0         1  56.065753    1  26.297578      1       1.0    0    0        0   
1         1  55.339726    1  33.208550      1       0.5    1    1        0   
2         1  75.786301    0  27.688778      1       6.0    1    0        1   
3         1  43.213699    0        NaN      1       1.0    0    0        0   
4         1  60.060274    0  26.927438      1       4.0    1    1        1   
5         1  49.194521    0  20.863177      1       1.0    1    1        0   
6         1  83.849315    0  21.875000      1      24.0    1    0        1   
7         1  44.194521    0  26.927438      1       1.0    1    0        0   
8         1  57.712329    0  36.810592      1      24.0    1    0        1   
9         1  76.471233    0  25.160698      1       1.0    1    0        0   
10        1  85.693151    1  30.116213      1       4.0    1    1        0   
11        1  70.523288    1  43.426532      1       5.0    1    0        0   
12        1  61.334247    1  35.896340      1       0.5    1    0        0   
13        1  66.487671    1  24.538965      1       2.0    0    0        0   
14        1  54.172603    1  37.460978      1       5.0    1    1        0   
15        1  78.210959    0  21.270630      1       4.0    1    0        0   
16        1  60.668493    0  32.046146      1       9.0    1    1        0   
17        1  66.487671    0  29.372397      1       0.5    1    1        0   
18        1  57.780822    0  39.736121      1       8.0    1    1        0   
19        1  73.328767    0  32.769395      1      12.0    1    1        0   
20        1  68.246575    0  28.928337      1      20.0    0    0        0   
21        1  51.863014    1  36.204986      1       4.0    1    1        1   
22        1  67.317808    1  32.911223      1       6.0    0    1        0   
23        1  58.641096    0  28.378215      1      22.0    0    0        0   
24        1  46.224658    0  43.359375      1       5.0    1    0        0   
25        1  64.191781    1  30.137993      1      15.0    1    0        0   
26        1  67.298630    0  34.894399      1      15.0    1    0        0   
27        1  54.134247    1  28.216134      1       4.0    1    0        0   
28        1  55.279452    0  27.767098      1       2.0    0    0        0   
29        1  59.038356    1  30.835753      1      19.0    1    0        0   
..      ...        ...  ...        ...    ...       ...  ...  ...      ...   
219       1  62.167123    1  29.462280      1      20.0    1    0        1   
220       1  71.208219    1  25.794163      1       7.0    1    1        1   
221       4  70.808219    0  35.916121      1      10.0    1    1        1   
222       1  61.791781    0  28.387441      1      28.0    1    1        0   
223       2  75.904110    1  28.400548      1      20.0    1    1        1   
224       1  74.621918    1  22.002551      1       9.0    1    0        0   
225       1  78.569863    1  26.464394      1      23.0    1    1        1   
226       2  66.695890    1  27.922368      1      20.0    1    1        1   
227       2  71.794521    1  27.335640      1       NaN    1    1        1   
228       1  78.756164    1  26.928180      1      31.0    1    0        0   
229       1  66.695890    1  29.420408      1      12.0    0    1        1   
230       1  58.997260    1  30.056811      1      40.0    1    1        0   
231       1  64.972603    0  31.265812      1      27.0    1    1        0   
232       4  44.087671    1  25.099502      1       4.0    1    0        0   
233       1  57.345205    1  35.019925      1      10.0    1    1        1   
234       1  45.884932    1  27.758490      0      43.0    1    1        1   
235       1  53.219178    0  27.239224      1      13.0    1    1        0   
236       4  75.230137    1  26.775510      1      12.0    1    0        0   
237       1  71.386301    1  31.441690      1      25.0    1    0        1   
238       2  58.142466    0

In [9]:
# Remove rows where taget are missing
missing_row = df['death'].isnull()
print('Number of rows where target are missing:')
print(sum(missing_row))

df = df[~missing_row]
df

Number of rows where target are missing:
0


center        age  sex        BMI  type2  duration  HTN  HLP  vascinc  \
0         1  56.065753    1  26.297578      1       1.0    0    0        0   
1         1  55.339726    1  33.208550      1       0.5    1    1        0   
2         1  75.786301    0  27.688778      1       6.0    1    0        1   
3         1  43.213699    0        NaN      1       1.0    0    0        0   
4         1  60.060274    0  26.927438      1       4.0    1    1        1   
5         1  49.194521    0  20.863177      1       1.0    1    1        0   
6         1  83.849315    0  21.875000      1      24.0    1    0        1   
7         1  44.194521    0  26.927438      1       1.0    1    0        0   
8         1  57.712329    0  36.810592      1      24.0    1    0        1   
9         1  76.471233    0  25.160698      1       1.0    1    0        0   
10        1  85.693151    1  30.116213      1       4.0    1    1        0   
11        1  70.523288    1  43.426532      1       5.0    1    0        0   
12        1  61.334247    1  35.896340      1       0.5    1    0        0   
13        1  66.487671    1  24.538965      1       2.0    0    0        0   
14        1  54.172603    1  37.460978      1       5.0    1    1        0   
15        1  78.210959    0  21.270630      1       4.0    1    0        0   
16        1  60.668493    0  32.046146      1       9.0    1    1        0   
17        1  66.487671    0  29.372397      1       0.5    1    1        0   
18        1  57.780822    0  39.736121      1       8.0    1    1        0   
19        1  73.328767    0  32.769395      1      12.0    1    1        0   
20        1  68.246575    0  28.928337      1      20.0    0    0        0   
21        1  51.863014    1  36.204986      1       4.0    1    1        1   
22        1  67.317808    1  32.911223      1       6.0    0    1        0   
23        1  58.641096    0  28.378215      1      22.0    0    0        0   
24        1  46.224658    0  43.359375      1       5.0    1    0        0   
25        1  64.191781    1  30.137993      1      15.0    1    0        0   
26        1  67.298630    0  34.894399      1      15.0    1    0        0   
27        1  54.134247    1  28.216134      1       4.0    1    0        0   
28        1  55.279452    0  27.767098      1       2.0    0    0        0   
29        1  59.038356    1  30.835753      1      19.0    1    0        0   
..      ...        ...  ...        ...    ...       ...  ...  ...      ...   
219       1  62.167123    1  29.462280      1      20.0    1    0        1   
220       1  71.208219    1  25.794163      1       7.0    1    1        1   
221       4  70.808219    0  35.916121      1      10.0    1    1        1   
222       1  61.791781    0  28.387441      1      28.0    1    1        0   
223       2  75.904110    1  28.400548      1      20.0    1    1        1   
224       1  74.621918    1  22.002551      1       9.0    1    0        0   
225       1  78.569863    1  26.464394      1      23.0    1    1        1   
226       2  66.695890    1  27.922368      1      20.0    1    1        1   
227       2  71.794521    1  27.335640      1       NaN    1    1        1   
228       1  78.756164    1  26.928180      1      31.0    1    0        0   
229       1  66.695890    1  29.420408      1      12.0    0    1        1   
230       1  58.997260    1  30.056811      1      40.0    1    1        0   
231       1  64.972603    0  31.265812      1      27.0    1    1        0   
232       4  44.087671    1  25.099502      1       4.0    1    0        0   
233       1  57.345205    1  35.019925      1      10.0    1    1        1   
234       1  45.884932    1  27.758490      0      43.0    1    1        1   
235       1  53.219178    0  27.239224      1      13.0    1    1        0   
236       4  75.230137    1  26.775510      1      12.0    1    0        0   
237       1  71.386301    1  31.441690      1      25.0    1    0        1   
238       2  58.142466    0

We determine and drop the variables with excessive missing values from the dataset.

In [10]:
def remove_bad_columns(df,bad_column_threshold):
    # find bad columns having too many missing values
    n_null = np.array(df.isnull().sum(axis=0))
    bad_col = np.array([]).astype(int)
    for i in range(len(n_null)):
        if n_null[i] >= bad_column_threshold:
            bad_col = np.append(bad_col,i)

    #print(bad_col)
    print('number of bad columns:',len(bad_col))

    # delete bad columns
    df = df.drop(df.columns[bad_col],axis=1)
    #df.info()
    return df   

In [11]:
df = remove_bad_columns(df,41)
df.info()

number of bad columns: 2
<class 'pandas.core.frame.DataFrame'>
Int64Index: 249 entries, 0 to 248
Data columns (total 39 columns):
center              249 non-null int64
age                 249 non-null float64
sex                 249 non-null int64
BMI                 246 non-null float64
type2               249 non-null int64
duration            240 non-null float64
HTN                 249 non-null int64
HLP                 249 non-null int64
vascinc             249 non-null int64
ACE                 248 non-null float64
ARB                 248 non-null float64
statin              248 non-null float64
hb                  240 non-null float64
CRP                 232 non-null float64
alb                 235 non-null float64
HbA1c               238 non-null float64
ferritin            235 non-null float64
EPO                 242 non-null float64
chol                230 non-null float64
LDL                 228 non-null float64
HDL                 229 non-null float64
hepcidin_ngml       2

We find bad rows which contain too many missing values, then remove them.

In [12]:
def remove_bad_rows(df,bad_row_threshold):   
    # find bad rows having too many missing values
    n_null = np.array(df.isnull().sum(axis=1))
    bad_row = np.array([]).astype(int)
    for t in range(len(n_null)):
        if n_null[t] >= bad_row_threshold:
            bad_row = np.append(bad_row,t)

    #print(bad_row)
    print('number of bad rows:',len(bad_row))

    # delete bad rows
    df = df.drop(bad_row)
    #df.info()
    return df

In [13]:
df = remove_bad_rows(df,6)
df.info()

number of bad rows: 13
<class 'pandas.core.frame.DataFrame'>
Int64Index: 236 entries, 0 to 248
Data columns (total 39 columns):
center              236 non-null int64
age                 236 non-null float64
sex                 236 non-null int64
BMI                 233 non-null float64
type2               236 non-null int64
duration            228 non-null float64
HTN                 236 non-null int64
HLP                 236 non-null int64
vascinc             236 non-null int64
ACE                 235 non-null float64
ARB                 235 non-null float64
statin              235 non-null float64
hb                  228 non-null float64
CRP                 227 non-null float64
alb                 228 non-null float64
HbA1c               227 non-null float64
ferritin            229 non-null float64
EPO                 233 non-null float64
chol                226 non-null float64
LDL                 224 non-null float64
HDL                 225 non-null float64
hepcidin_ngml       236

For convenience, we separate independents `X` and dependent `y` from the data.

In [14]:
dfx = df.drop('death',axis=1)
dfy = df['death']

In [15]:
# number of uniques of each column (excluding NaN)
nu = np.array([len(pd.unique(dfx[col].dropna())) for col in dfx.columns])
print('number of uniques of each variable:')
print(nu)

number of uniques of each variable:
[  4 231   2 226   2  42   2   2   2   2   2   2  79 116 122  55 175 153
 124 110  59 124 236 236 184  98 210   2 206   3   2 114 195 111  99   2
   2 214]


In [16]:
def define_variable_type(df,nu):
    i_binary = [] ; i_category = [] ; i_continuous = []
    for i in range(len(nu)):
        if nu[i] == 2: # binary 
            i_binary.append(i)
        elif nu[i] < 5: # !!!! NOTE: this is not always correct, depending on data
            i_category.append(i)
        else:
            i_continuous.append(i)

    print('i_binary:',i_binary)
    print('i_category:',i_category)   
    #i_binary, i_category, i_continuous
    
    variable_type  = np.ones(len(nu))  # binary
    variable_type[i_category] = 2   # categorical
    variable_type[i_continuous] = 3 # continuous

    return variable_type #,i_binary,i_category,i_continuous

In [17]:
variable_type = define_variable_type(dfx,nu)
print('variable type:',variable_type)

i_binary: [2, 4, 6, 7, 8, 9, 10, 11, 27, 30, 35, 36]
i_category: [0, 29]
variable type: [2. 3. 1. 3. 1. 3. 1. 1. 1. 1. 1. 1. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.
 3. 3. 3. 1. 3. 2. 1. 3. 3. 3. 3. 1. 1. 3.]


In [18]:
def impute_missing(df,variable_type):
    # impute binary and categorical variables by the most frequency (in each column)
    # continuous variable by median
    # input: df: pandas data frame, variable_type: list
    # output: df2: pandas data frame
    df2 = df.copy()
    for i,col in enumerate(df.columns):
        if variable_type[i] < 3: # binary or caterogy
            df2[col] = df[col].fillna(df[col].mode().iloc[0])
        else: # continuous
            df2[col] = df[col].fillna(df[col].median())    
    return df2       

In [19]:
dfx_imputed = impute_missing(dfx,variable_type)
dfx_imputed

center        age  sex        BMI  type2  duration  HTN  HLP  vascinc  \
0         1  56.065753    1  26.297578      1       1.0    0    0        0   
1         1  55.339726    1  33.208550      1       0.5    1    1        0   
2         1  75.786301    0  27.688778      1       6.0    1    0        1   
3         1  43.213699    0  29.458219      1       1.0    0    0        0   
4         1  60.060274    0  26.927438      1       4.0    1    1        1   
5         1  49.194521    0  20.863177      1       1.0    1    1        0   
6         1  83.849315    0  21.875000      1      24.0    1    0        1   
7         1  44.194521    0  26.927438      1       1.0    1    0        0   
8         1  57.712329    0  36.810592      1      24.0    1    0        1   
9         1  76.471233    0  25.160698      1       1.0    1    0        0   
10        1  85.693151    1  30.116213      1       4.0    1    1        0   
11        1  70.523288    1  43.426532      1       5.0    1    0        0   
12        1  61.334247    1  35.896340      1       0.5    1    0        0   
13        1  66.487671    1  24.538965      1       2.0    0    0        0   
14        1  54.172603    1  37.460978      1       5.0    1    1        0   
15        1  78.210959    0  21.270630      1       4.0    1    0        0   
16        1  60.668493    0  32.046146      1       9.0    1    1        0   
17        1  66.487671    0  29.372397      1       0.5    1    1        0   
18        1  57.780822    0  39.736121      1       8.0    1    1        0   
19        1  73.328767    0  32.769395      1      12.0    1    1        0   
20        1  68.246575    0  28.928337      1      20.0    0    0        0   
21        1  51.863014    1  36.204986      1       4.0    1    1        1   
22        1  67.317808    1  32.911223      1       6.0    0    1        0   
23        1  58.641096    0  28.378215      1      22.0    0    0        0   
24        1  46.224658    0  43.359375      1       5.0    1    0        0   
25        1  64.191781    1  30.137993      1      15.0    1    0        0   
26        1  67.298630    0  34.894399      1      15.0    1    0        0   
27        1  54.134247    1  28.216134      1       4.0    1    0        0   
28        1  55.279452    0  27.767098      1       2.0    0    0        0   
29        1  59.038356    1  30.835753      1      19.0    1    0        0   
..      ...        ...  ...        ...    ...       ...  ...  ...      ...   
213       2  66.158904    0  26.026175      1      29.0    0    0        1   
214       1  60.682192    1  29.037775      0      33.0    0    1        0   
215       1  57.780822    1  34.717839      1      14.0    1    1        0   
216       1  77.134247    1  36.540022      1       6.0    1    0        0   
218       2  44.243836    0  29.458219      0      30.0    0    1        0   
219       1  62.167123    1  29.462280      1      20.0    1    0        1   
220       1  71.208219    1  25.794163      1       7.0    1    1        1   
221       4  70.808219    0  35.916121      1      10.0    1    1        1   
223       2  75.904110    1  28.400548      1      20.0    1    1        1   
224       1  74.621918    1  22.002551      1       9.0    1    0        0   
225       1  78.569863    1  26.464394      1      23.0    1    1        1   
226       2  66.695890    1  27.922368      1      20.0    1    1        1   
227       2  71.794521    1  27.335640      1      10.0    1    1        1   
228       1  78.756164    1  26.928180      1      31.0    1    0        0   
230       1  58.997260    1  30.056811      1      40.0    1    1        0   
231       1  64.972603    0  31.265812      1      27.0    1    1        0   
233       1  57.345205    1  35.019925      1      10.0    1    1        1   
234       1  45.884932    1  27.758490      0      43.0    1    1        1   
235       1  53.219178    0  27.239224      1      13.0    1    1        0   
236       4  75.230137    1

In [20]:
dfx_imputed.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 236 entries, 0 to 248
Data columns (total 38 columns):
center              236 non-null int64
age                 236 non-null float64
sex                 236 non-null int64
BMI                 236 non-null float64
type2               236 non-null int64
duration            236 non-null float64
HTN                 236 non-null int64
HLP                 236 non-null int64
vascinc             236 non-null int64
ACE                 236 non-null float64
ARB                 236 non-null float64
statin              236 non-null float64
hb                  236 non-null float64
CRP                 236 non-null float64
alb                 236 non-null float64
HbA1c               236 non-null float64
ferritin            236 non-null float64
EPO                 236 non-null float64
chol                236 non-null float64
LDL                 236 non-null float64
HDL                 236 non-null float64
hepcidin_ngml       236 non-null float64
CKDEP

## Data Processing

### Attributes

In [21]:
def convert_binary_and_category(x,variable_type):
    """
    convert binary to +-1, category to one hot; remain continuous.
    """
    
    onehot_encoder = OneHotEncoder(sparse=False,categories='auto')

    # create 2 initial columns
    x_new = np.zeros((x.shape[0],2))

    for i,i_type in enumerate(variable_type):
        if i_type == 1: # binary
            unique_value = np.unique(x[:,i])
            x1 = np.array([-1. if value == unique_value[0] else 1. for value in x[:,i]])        
            x_new = np.hstack((x_new,x1[:,np.newaxis]))

        elif i_type == 2: # category
            x1 = onehot_encoder.fit_transform(x[:,i].reshape(-1,1))
            x_new = np.hstack((x_new,x1))
            
        else: # continuous      
            x_new = np.hstack((x_new,x[:,i][:,np.newaxis]))      

    # drop the 2 initial column
    x_new = x_new[:,2:]
    
    return x_new.astype(float)

In [22]:
# convert x
x = np.array(dfx_imputed)
x_new = convert_binary_and_category(x,variable_type)

print(x_new.shape)
print(x_new)

(236, 43)
[[ 1.000e+00  0.000e+00  0.000e+00 ... -1.000e+00 -1.000e+00  2.204e+03]
 [ 1.000e+00  0.000e+00  0.000e+00 ... -1.000e+00 -1.000e+00  2.000e+00]
 [ 1.000e+00  0.000e+00  0.000e+00 ... -1.000e+00 -1.000e+00  1.000e+00]
 ...
 [ 1.000e+00  0.000e+00  0.000e+00 ... -1.000e+00  1.000e+00  7.600e+01]
 [ 1.000e+00  0.000e+00  0.000e+00 ... -1.000e+00  1.000e+00  4.660e+02]
 [ 0.000e+00  1.000e+00  0.000e+00 ... -1.000e+00 -1.000e+00  1.694e+03]]


### Target

In [23]:
y = np.array(dfy)
print(np.unique(y,return_counts=True))

# if target is already 0 and 1
y_new = y #and delete lines below convert  
print(np.unique(y_new,return_counts=True))

(array([0, 1]), array([193,  43]))
(array([0, 1]), array([193,  43]))


In [24]:
# combine X and y and save to a file
xy_new = np.hstack((x_new,y_new[:,np.newaxis]))
np.savetxt('anemia_processed.dat',xy_new,fmt='%f')