In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
#from sklearn.preprocessing import Imputer

In [2]:
np.random.seed(1)

In [3]:
df = pd.read_csv("mental.csv")
df

id  school_year  semester   age gender  height  weight  phq1  phq2  \
0      A1            1         1  19.0      m    1.50    75.0   2.0   1.0   
1      B2            1         1  18.0      m    1.68    56.0   2.0   0.0   
2      C3            1         1  19.0      m    1.74    76.0   1.0   1.0   
3      D4            1         1  18.0      f    1.68    67.0   2.0   2.0   
4      E5            1         1  18.0      m    1.80    83.0   0.0   1.0   
5      F6            1         1  18.0      m    1.74    67.0   0.0   0.0   
6      G7            1         1  18.0      m    1.78    71.0   1.0   0.0   
7      H8            1         1  19.0      m    1.69    58.5   0.0   0.0   
8      I9            1         1  20.0      m    1.55    51.0   1.0   1.0   
9     J10            1         1  19.0      m    1.75    75.0   1.0   1.0   
10    K11            1         1  18.0      m    1.86    80.0   0.0   0.0   
11    L12            1         1  18.0      f     NaN    59.0   3.0   1.0   
12    M13            1         1  19.0      m    1.76    89.0   1.0   0.0   
13    N14            1         1  18.0      m    1.74    69.0   1.0   1.0   
14    O15            1         1  18.0      m    1.70    66.0   0.0   0.0   
15    P16            1         1  18.0      m    1.75    60.0   1.0   1.0   
16    Q17            1         1  18.0      f    1.62    58.0   1.0   1.0   
17    R18            1         1  18.0      f    1.58    60.0   1.0   1.0   
18    S19            1         1  18.0      m    1.78    66.0   3.0   1.0   
19    T20            1         1  18.0      m    1.70    79.0   1.0   0.0   
20    U21            1         1  18.0      m    1.77    65.0   2.0   1.0   
21    V22            1         1  18.0      f    1.60    68.0   1.0   2.0   
22    W23            1         1  19.0      m    1.85    92.0   1.0   2.0   
23    X24            1         1  19.0      f    1.62    64.0   0.0   1.0   
24    Y25            1         1  18.0      m    1.69    65.0   1.0   1.0   
25    Z26            1         1  18.0      m    1.78    76.0   1.0   0.0   
26    A27            1         1  19.0      m    1.78    78.5   1.0   2.0   
27    B28            1         1  18.0      f    1.60    64.0   1.0   1.0   
28    C29            1         1  19.0      f    1.64    54.0   1.0   0.0   
29    D30            1         1  18.0      f    1.80    70.0   0.0   0.0   
..    ...          ...       ...   ...    ...     ...     ...   ...   ...   
746  S747            4         8  22.0      f    1.54    59.0   1.0   1.0   
747  T748            4         8  22.0      f    1.65    70.0   1.0   1.0   
748  U749            4         8  23.0      m    1.76    90.0   1.0   0.0   
749  V750            4         8  22.0      m    1.80    85.0   1.0   0.0   
750  W751            4         8  22.0      f    1.65    51.0   1.0   0.0   
751  X752            4         8  24.0      f    1.57    59.0   1.0   1.0   
752  Y753            4         8  22.0      f    1.75    86.0   2.0   2.0   
753  Z754            4         8  22.0      f    1.59    63.0   3.0   3.0   
754  A755            4         8  22.0      f    1.69    89.5   1.0   0.0   
755  B756            4         8  22.0      m    1.74    68.0   1.0   1.0   
756  C757            4         8  23.0      m    1.80    75.0   0.0   0.0   
757  D758            4         8  24.0      m    1.70    82.0   2.0   1.0   
758  E759            4         8  23.0      m    1.66    47.0   1.0   1.0   
759  F760            4         8  24.0      f    1.76    87.0   1.0   0.0   
760  G761            4         8  23.0      f    1.54    60.0   2.0   1.0   
761  H762            4         8  22.0      f    1.54    62.0   1.0   2.0   
762  I763            4         8  22.0      m    1.83    93.0   1.0   0.0   
763  J764            4         8  21.0      m    1.83    91.0   2.0   0.0   
764  K765            4         8  22.0      f    1.65    60.0   1.0   1.0   
765  L766            4         8  23.0      m    1.79    72.0   1.0   1.0   
766

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 776 entries, 0 to 775
Columns: 255 entries, id to Unnamed: 254
dtypes: float64(246), int64(2), object(7)
memory usage: 1.5+ MB


## Data Cleaning

In [5]:
# Drop several columns as they are either unrelated or not formatted to the dependent variable
df = df.drop(['id','gender','bed_time','wake_up_time','reported_sleep_hours','nap_duration','weekly_study_hours'],axis=1)
df

school_year  semester   age  height  weight  phq1  phq2  phq3  phq4  \
0              1         1  19.0    1.50    75.0   2.0   1.0   1.0   1.0   
1              1         1  18.0    1.68    56.0   2.0   0.0   1.0   2.0   
2              1         1  19.0    1.74    76.0   1.0   1.0   0.0   3.0   
3              1         1  18.0    1.68    67.0   2.0   2.0   3.0   3.0   
4              1         1  18.0    1.80    83.0   0.0   1.0   1.0   2.0   
5              1         1  18.0    1.74    67.0   0.0   0.0   0.0   1.0   
6              1         1  18.0    1.78    71.0   1.0   0.0   2.0   2.0   
7              1         1  19.0    1.69    58.5   0.0   0.0   1.0   1.0   
8              1         1  20.0    1.55    51.0   1.0   1.0   3.0   1.0   
9              1         1  19.0    1.75    75.0   1.0   1.0   0.0   1.0   
10             1         1  18.0    1.86    80.0   0.0   0.0   0.0   1.0   
11             1         1  18.0     NaN    59.0   3.0   1.0   1.0   1.0   
12             1         1  19.0    1.76    89.0   1.0   0.0   2.0   2.0   
13             1         1  18.0    1.74    69.0   1.0   1.0   1.0   0.0   
14             1         1  18.0    1.70    66.0   0.0   0.0   3.0   3.0   
15             1         1  18.0    1.75    60.0   1.0   1.0   0.0   1.0   
16             1         1  18.0    1.62    58.0   1.0   1.0   1.0   1.0   
17             1         1  18.0    1.58    60.0   1.0   1.0   2.0   1.0   
18             1         1  18.0    1.78    66.0   3.0   1.0   1.0   0.0   
19             1         1  18.0    1.70    79.0   1.0   0.0   1.0   1.0   
20             1         1  18.0    1.77    65.0   2.0   1.0   0.0   1.0   
21             1         1  18.0    1.60    68.0   1.0   2.0   0.0   0.0   
22             1         1  19.0    1.85    92.0   1.0   2.0   2.0   2.0   
23             1         1  19.0    1.62    64.0   0.0   1.0   0.0   1.0   
24             1         1  18.0    1.69    65.0   1.0   1.0   1.0   1.0   
25             1         1  18.0    1.78    76.0   1.0   0.0   1.0   1.0   
26             1         1  19.0    1.78    78.5   1.0   2.0   0.0   1.0   
27             1         1  18.0    1.60    64.0   1.0   1.0   2.0   3.0   
28             1         1  19.0    1.64    54.0   1.0   0.0   0.0   0.0   
29             1         1  18.0    1.80    70.0   0.0   0.0   0.0   1.0   
..           ...       ...   ...     ...     ...   ...   ...   ...   ...   
746            4         8  22.0    1.54    59.0   1.0   1.0   1.0   1.0   
747            4         8  22.0    1.65    70.0   1.0   1.0   3.0   1.0   
748            4         8  23.0    1.76    90.0   1.0   0.0   1.0   1.0   
749            4         8  22.0    1.80    85.0   1.0   0.0   1.0   1.0   
750            4         8  22.0    1.65    51.0   1.0   0.0   1.0   2.0   
751            4         8  24.0    1.57    59.0   1.0   1.0   0.0   1.0   
752            4         8  22.0    1.75    86.0   2.0   2.0   1.0   1.0   
753            4         8  22.0    1.59    63.0   3.0   3.0   3.0   3.0   
754            4         8  22.0    1.69    89.5   1.0   0.0   0.0   0.0   
755            4         8  22.0    1.74    68.0   1.0   1.0   1.0   1.0   
756            4         8  23.0    1.80    75.0   0.0   0.0   1.0   0.0   
757            4         8  24.0    1.70    82.0   2.0   1.0   2.0   2.0   
758            4         8  23.0    1.66    47.0   1.0   1.0   2.0   1.0   
759            4         8  24.0    1.76    87.0   1.0   0.0   0.0   1.0   
760            4         8  23.0    1.54    60.0   2.0   1.0   0.0   1.0   
761            4         8  22.0    1.54    62.0   1.0   2.0   1.0   2.0   
762            4         8  22.0    1.83    93.0   1.0   0.0   1.0   1.0   
763            4         8  21.0    1.83    91.0   2.0   0.0   0.0   1.0   
764            4         8  22.0    1.65    60.0   1.0   1.0   1.0   1.0   
765            4         8  23.0    1.79    72.0   1.0   1.0   1.0   1.0   
766            4         8  22.0    1.63    48.0   0.

In [6]:
# Remove rows where taget are missing
missing_row = df['thoughts_of_dropping_out'].isnull()
print('Number of rows where target are missing:')
print(sum(missing_row))

df = df[~missing_row]
df

Number of rows where target are missing:
5


school_year  semester   age  height  weight  phq1  phq2  phq3  phq4  \
0              1         1  19.0    1.50    75.0   2.0   1.0   1.0   1.0   
1              1         1  18.0    1.68    56.0   2.0   0.0   1.0   2.0   
2              1         1  19.0    1.74    76.0   1.0   1.0   0.0   3.0   
3              1         1  18.0    1.68    67.0   2.0   2.0   3.0   3.0   
4              1         1  18.0    1.80    83.0   0.0   1.0   1.0   2.0   
5              1         1  18.0    1.74    67.0   0.0   0.0   0.0   1.0   
6              1         1  18.0    1.78    71.0   1.0   0.0   2.0   2.0   
7              1         1  19.0    1.69    58.5   0.0   0.0   1.0   1.0   
8              1         1  20.0    1.55    51.0   1.0   1.0   3.0   1.0   
9              1         1  19.0    1.75    75.0   1.0   1.0   0.0   1.0   
10             1         1  18.0    1.86    80.0   0.0   0.0   0.0   1.0   
11             1         1  18.0     NaN    59.0   3.0   1.0   1.0   1.0   
12             1         1  19.0    1.76    89.0   1.0   0.0   2.0   2.0   
13             1         1  18.0    1.74    69.0   1.0   1.0   1.0   0.0   
14             1         1  18.0    1.70    66.0   0.0   0.0   3.0   3.0   
15             1         1  18.0    1.75    60.0   1.0   1.0   0.0   1.0   
16             1         1  18.0    1.62    58.0   1.0   1.0   1.0   1.0   
17             1         1  18.0    1.58    60.0   1.0   1.0   2.0   1.0   
18             1         1  18.0    1.78    66.0   3.0   1.0   1.0   0.0   
19             1         1  18.0    1.70    79.0   1.0   0.0   1.0   1.0   
20             1         1  18.0    1.77    65.0   2.0   1.0   0.0   1.0   
21             1         1  18.0    1.60    68.0   1.0   2.0   0.0   0.0   
22             1         1  19.0    1.85    92.0   1.0   2.0   2.0   2.0   
23             1         1  19.0    1.62    64.0   0.0   1.0   0.0   1.0   
24             1         1  18.0    1.69    65.0   1.0   1.0   1.0   1.0   
25             1         1  18.0    1.78    76.0   1.0   0.0   1.0   1.0   
26             1         1  19.0    1.78    78.5   1.0   2.0   0.0   1.0   
27             1         1  18.0    1.60    64.0   1.0   1.0   2.0   3.0   
28             1         1  19.0    1.64    54.0   1.0   0.0   0.0   0.0   
29             1         1  18.0    1.80    70.0   0.0   0.0   0.0   1.0   
..           ...       ...   ...     ...     ...   ...   ...   ...   ...   
746            4         8  22.0    1.54    59.0   1.0   1.0   1.0   1.0   
747            4         8  22.0    1.65    70.0   1.0   1.0   3.0   1.0   
748            4         8  23.0    1.76    90.0   1.0   0.0   1.0   1.0   
749            4         8  22.0    1.80    85.0   1.0   0.0   1.0   1.0   
750            4         8  22.0    1.65    51.0   1.0   0.0   1.0   2.0   
751            4         8  24.0    1.57    59.0   1.0   1.0   0.0   1.0   
752            4         8  22.0    1.75    86.0   2.0   2.0   1.0   1.0   
753            4         8  22.0    1.59    63.0   3.0   3.0   3.0   3.0   
754            4         8  22.0    1.69    89.5   1.0   0.0   0.0   0.0   
755            4         8  22.0    1.74    68.0   1.0   1.0   1.0   1.0   
756            4         8  23.0    1.80    75.0   0.0   0.0   1.0   0.0   
757            4         8  24.0    1.70    82.0   2.0   1.0   2.0   2.0   
758            4         8  23.0    1.66    47.0   1.0   1.0   2.0   1.0   
759            4         8  24.0    1.76    87.0   1.0   0.0   0.0   1.0   
760            4         8  23.0    1.54    60.0   2.0   1.0   0.0   1.0   
761            4         8  22.0    1.54    62.0   1.0   2.0   1.0   2.0   
762            4         8  22.0    1.83    93.0   1.0   0.0   1.0   1.0   
763            4         8  21.0    1.83    91.0   2.0   0.0   0.0   1.0   
764            4         8  22.0    1.65    60.0   1.0   1.0   1.0   1.0   
765            4         8  23.0    1.79    72.0   1.0   1.0   1.0   1.0   
766            4         8  22.0    1.63    48.0   0.

We determine and drop the variables with excessive missing values from the dataset.

In [7]:
def remove_bad_columns(df,bad_column_threshold):
    # find bad columns having too many missing values
    n_null = np.array(df.isnull().sum(axis=0))
    bad_col = np.array([]).astype(int)
    for i in range(len(n_null)):
        if n_null[i] >= bad_column_threshold:
            bad_col = np.append(bad_col,i)

    #print(bad_col)
    print('number of bad columns:',len(bad_col))

    # delete bad columns
    df = df.drop(df.columns[bad_col],axis=1)
    #df.info()
    return df   

In [8]:
df = remove_bad_columns(df,16)
df.info()

number of bad columns: 213
<class 'pandas.core.frame.DataFrame'>
Int64Index: 771 entries, 0 to 775
Data columns (total 35 columns):
school_year                      771 non-null int64
semester                         771 non-null int64
age                              771 non-null float64
height                           766 non-null float64
weight                           767 non-null float64
phq1                             770 non-null float64
phq2                             770 non-null float64
phq3                             770 non-null float64
phq4                             770 non-null float64
phq5                             767 non-null float64
phq6                             770 non-null float64
phq7                             770 non-null float64
phq8                             770 non-null float64
phq9                             770 non-null float64
thoughts_of_dropping_out         771 non-null float64
previous_depression_diagnosis    770 non-null float64
previous

We find bad rows which contain too many missing values, then remove them.

In [9]:
def remove_bad_rows(df,bad_row_threshold):   
    # find bad rows having too many missing values
    n_null = np.array(df.isnull().sum(axis=1))
    bad_row = np.array([]).astype(int)
    for t in range(len(n_null)):
        if n_null[t] >= bad_row_threshold:
            bad_row = np.append(bad_row,t)

    #print(bad_row)
    print('number of bad rows:',len(bad_row))

    # delete bad rows
    df = df.drop(bad_row)
    #df.info()
    return df

In [10]:
df = remove_bad_rows(df,6)
df.info()

number of bad rows: 8
<class 'pandas.core.frame.DataFrame'>
Int64Index: 763 entries, 0 to 775
Data columns (total 35 columns):
school_year                      763 non-null int64
semester                         763 non-null int64
age                              763 non-null float64
height                           758 non-null float64
weight                           759 non-null float64
phq1                             762 non-null float64
phq2                             762 non-null float64
phq3                             762 non-null float64
phq4                             762 non-null float64
phq5                             759 non-null float64
phq6                             762 non-null float64
phq7                             762 non-null float64
phq8                             762 non-null float64
phq9                             762 non-null float64
thoughts_of_dropping_out         763 non-null float64
previous_depression_diagnosis    762 non-null float64
previous_depr

In [11]:
dfx = df.drop('thoughts_of_dropping_out',axis=1)
dfy = df['thoughts_of_dropping_out']

In [12]:
# number of uniques of each column (excluding NaN)
nu = np.array([len(pd.unique(dfx[col].dropna())) for col in dfx.columns])
print('number of uniques of each variable:')
print(nu)

number of uniques of each variable:
[ 4  7 15 47 88  4  4  4  4  4  4  4  4  4  2  2  4  4  4  4  4  4  4  2
  2  5  5  5  5  5  5  5  5  5]


In [13]:
def define_variable_type(df,nu):
    i_binary = [] ; i_category = [] ; i_continuous = []
    for i in range(len(nu)):
        if nu[i] == 2: # binary 
            i_binary.append(i)
        elif nu[i] < 5: # !!!! NOTE: this is not always correct, depending on data
            i_category.append(i)
        else:
            i_continuous.append(i)

    print('i_binary:',i_binary)
    print('i_category:',i_category)   
    #i_binary, i_category, i_continuous
    
    variable_type  = np.ones(len(nu))  # binary
    variable_type[i_category] = 2   # categorical
    variable_type[i_continuous] = 3 # continuous

    return variable_type #,i_binary,i_category,i_continuous

In [14]:
variable_type = define_variable_type(dfx,nu)
print('variable type:',variable_type)

i_binary: [14, 15, 23, 24]
i_category: [0, 5, 6, 7, 8, 9, 10, 11, 12, 13, 16, 17, 18, 19, 20, 21, 22]
variable type: [2. 3. 3. 3. 3. 2. 2. 2. 2. 2. 2. 2. 2. 2. 1. 1. 2. 2. 2. 2. 2. 2. 2. 1.
 1. 3. 3. 3. 3. 3. 3. 3. 3. 3.]


In [15]:
def impute_missing(df,variable_type):
    # impute binary and categorical variables by the most frequency (in each column)
    # continuous variable by median
    # input: df: pandas data frame, variable_type: list
    # output: df2: pandas data frame
    df2 = df.copy()
    for i,col in enumerate(df.columns):
        if variable_type[i] < 3: # binary or caterogy
            df2[col] = df[col].fillna(df[col].mode().iloc[0])
        else: # continuous
            df2[col] = df[col].fillna(df[col].median())    
    return df2       

In [16]:
dfx_imputed = impute_missing(dfx,variable_type)
dfx_imputed

school_year  semester   age  height  weight  phq1  phq2  phq3  phq4  \
0              1         1  19.0    1.50    75.0   2.0   1.0   1.0   1.0   
1              1         1  18.0    1.68    56.0   2.0   0.0   1.0   2.0   
2              1         1  19.0    1.74    76.0   1.0   1.0   0.0   3.0   
3              1         1  18.0    1.68    67.0   2.0   2.0   3.0   3.0   
4              1         1  18.0    1.80    83.0   0.0   1.0   1.0   2.0   
5              1         1  18.0    1.74    67.0   0.0   0.0   0.0   1.0   
6              1         1  18.0    1.78    71.0   1.0   0.0   2.0   2.0   
7              1         1  19.0    1.69    58.5   0.0   0.0   1.0   1.0   
8              1         1  20.0    1.55    51.0   1.0   1.0   3.0   1.0   
9              1         1  19.0    1.75    75.0   1.0   1.0   0.0   1.0   
10             1         1  18.0    1.86    80.0   0.0   0.0   0.0   1.0   
11             1         1  18.0    1.69    59.0   3.0   1.0   1.0   1.0   
12             1         1  19.0    1.76    89.0   1.0   0.0   2.0   2.0   
13             1         1  18.0    1.74    69.0   1.0   1.0   1.0   0.0   
14             1         1  18.0    1.70    66.0   0.0   0.0   3.0   3.0   
15             1         1  18.0    1.75    60.0   1.0   1.0   0.0   1.0   
16             1         1  18.0    1.62    58.0   1.0   1.0   1.0   1.0   
17             1         1  18.0    1.58    60.0   1.0   1.0   2.0   1.0   
18             1         1  18.0    1.78    66.0   3.0   1.0   1.0   0.0   
19             1         1  18.0    1.70    79.0   1.0   0.0   1.0   1.0   
20             1         1  18.0    1.77    65.0   2.0   1.0   0.0   1.0   
21             1         1  18.0    1.60    68.0   1.0   2.0   0.0   0.0   
22             1         1  19.0    1.85    92.0   1.0   2.0   2.0   2.0   
23             1         1  19.0    1.62    64.0   0.0   1.0   0.0   1.0   
24             1         1  18.0    1.69    65.0   1.0   1.0   1.0   1.0   
25             1         1  18.0    1.78    76.0   1.0   0.0   1.0   1.0   
26             1         1  19.0    1.78    78.5   1.0   2.0   0.0   1.0   
27             1         1  18.0    1.60    64.0   1.0   1.0   2.0   3.0   
28             1         1  19.0    1.64    54.0   1.0   0.0   0.0   0.0   
30             1         1  20.0    1.50    64.0   1.0   3.0   1.0   2.0   
..           ...       ...   ...     ...     ...   ...   ...   ...   ...   
746            4         8  22.0    1.54    59.0   1.0   1.0   1.0   1.0   
747            4         8  22.0    1.65    70.0   1.0   1.0   3.0   1.0   
748            4         8  23.0    1.76    90.0   1.0   0.0   1.0   1.0   
749            4         8  22.0    1.80    85.0   1.0   0.0   1.0   1.0   
750            4         8  22.0    1.65    51.0   1.0   0.0   1.0   2.0   
751            4         8  24.0    1.57    59.0   1.0   1.0   0.0   1.0   
752            4         8  22.0    1.75    86.0   2.0   2.0   1.0   1.0   
753            4         8  22.0    1.59    63.0   3.0   3.0   3.0   3.0   
754            4         8  22.0    1.69    89.5   1.0   0.0   0.0   0.0   
755            4         8  22.0    1.74    68.0   1.0   1.0   1.0   1.0   
756            4         8  23.0    1.80    75.0   0.0   0.0   1.0   0.0   
757            4         8  24.0    1.70    82.0   2.0   1.0   2.0   2.0   
758            4         8  23.0    1.66    47.0   1.0   1.0   2.0   1.0   
759            4         8  24.0    1.76    87.0   1.0   0.0   0.0   1.0   
760            4         8  23.0    1.54    60.0   2.0   1.0   0.0   1.0   
761            4         8  22.0    1.54    62.0   1.0   2.0   1.0   2.0   
762            4         8  22.0    1.83    93.0   1.0   0.0   1.0   1.0   
763            4         8  21.0    1.83    91.0   2.0   0.0   0.0   1.0   
764            4         8  22.0    1.65    60.0   1.0   1.0   1.0   1.0   
765            4         8  23.0    1.79    72.0   1.0   1.0   1.0   1.0   
766            4         8  22.0    1.63    48.0   0.

In [17]:
dfx_imputed.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 763 entries, 0 to 775
Data columns (total 34 columns):
school_year                      763 non-null int64
semester                         763 non-null int64
age                              763 non-null float64
height                           763 non-null float64
weight                           763 non-null float64
phq1                             763 non-null float64
phq2                             763 non-null float64
phq3                             763 non-null float64
phq4                             763 non-null float64
phq5                             763 non-null float64
phq6                             763 non-null float64
phq7                             763 non-null float64
phq8                             763 non-null float64
phq9                             763 non-null float64
previous_depression_diagnosis    763 non-null float64
previous_depression_treatment    763 non-null float64
gad1                             76

## Data Processing

### Attributes

In [18]:
def convert_binary_and_category(x,variable_type):
    """
    convert binary to +-1, category to one hot; remain continuous.
    """
    
    onehot_encoder = OneHotEncoder(sparse=False,categories='auto')

    # create 2 initial columns
    x_new = np.zeros((x.shape[0],2))

    for i,i_type in enumerate(variable_type):
        if i_type == 1: # binary
            unique_value = np.unique(x[:,i])
            x1 = np.array([-1. if value == unique_value[0] else 1. for value in x[:,i]])        
            x_new = np.hstack((x_new,x1[:,np.newaxis]))

        elif i_type == 2: # category
            x1 = onehot_encoder.fit_transform(x[:,i].reshape(-1,1))
            x_new = np.hstack((x_new,x1))
            
        else: # continuous      
            x_new = np.hstack((x_new,x[:,i][:,np.newaxis]))      

    # drop the 2 initial column
    x_new = x_new[:,2:]
    
    return x_new.astype(float)

In [19]:
# convert x
x = np.array(dfx_imputed)
x_new = convert_binary_and_category(x,variable_type)

print(x_new.shape)
print(x_new)

(763, 85)
[[1. 0. 0. ... 1. 1. 1.]
 [1. 0. 0. ... 2. 2. 2.]
 [1. 0. 0. ... 1. 1. 1.]
 ...
 [0. 0. 0. ... 1. 0. 1.]
 [0. 0. 0. ... 1. 3. 4.]
 [0. 0. 0. ... 0. 0. 4.]]


### Target

In [20]:
y = np.array(dfy)
print(np.unique(y,return_counts=True))



# if target is already 0 and 1
y_new = y #and delete lines below convert  
print(np.unique(y_new,return_counts=True))

(array([0., 1.]), array([614, 149]))
(array([0., 1.]), array([614, 149]))


In [21]:
# combine X and y and save to a file
xy_new = np.hstack((x_new,y_new[:,np.newaxis]))
np.savetxt('mental_processed.dat',xy_new,fmt='%f')