In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [2]:
np.random.seed(1)

In [3]:
df = pd.read_csv("ef.csv")
df.head()

sex  m32  m33_1   PE  m33_2  m34  m35  m35_1_2  m35_2_2  m35_1_3  ...  \
0    1    1    1.0  1.0    1.0    1    2      1.0     11.0    999.0  ...   
1    1  999    NaN  NaN    NaN    5    1      NaN      NaN      NaN  ...   
2    1    2    1.0  1.0    1.0    1    1      NaN      NaN      NaN  ...   
3    1    5    2.0  2.0    3.0    2    1      NaN      NaN      NaN  ...   
4    1   60    2.0  2.0   45.0    5    1      NaN      NaN      NaN  ...   

   IPE5  IPE6  IPE7  IPE8  IPE9  IPE10  Age_Categ  Age_recode_2  IIEF5_Categ  \
0   NaN   5.0   5.0   NaN   0.0    0.0        NaN           NaN          NaN   
1   NaN   2.0   1.0   NaN   0.0    0.0        1.0           1.0          NaN   
2   NaN   5.0   5.0   NaN   0.0    0.0        NaN           NaN          NaN   
3   NaN   1.0   1.0   NaN   0.0    0.0        3.0           3.0          NaN   
4   4.0   3.0   5.0   5.0   4.0    3.0        1.0           1.0          2.0   

   IIEF_Y_N  
0       NaN  
1       NaN  
2       NaN  
3       NaN  
4       1.0  

[5 rows x 55 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1004 entries, 0 to 1003
Data columns (total 55 columns):
sex                    1004 non-null int64
m32                    1004 non-null int64
m33_1                  920 non-null float64
PE                     816 non-null float64
m33_2                  816 non-null float64
m34                    1004 non-null int64
m35                    1004 non-null int64
m35_1_2                126 non-null float64
m35_2_2                43 non-null float64
m35_1_3                126 non-null float64
m35_2_3                46 non-null float64
m36_3                  133 non-null float64
m36_4                  133 non-null float64
m42                    1004 non-null int64
m43                    1004 non-null int64
m44                    1004 non-null int64
m45                    1004 non-null int64
m46                    1004 non-null int64
m47                    1004 non-null int64
m48                    1004 non-null int64
m49                    100

## Data Cleaning

In [5]:
target = 'IIEF_Y_N'

### Replace empty or errors by np.nan

In [6]:
# replace empty/erros by np.nan
df = df.replace(r'^\s+$', np.nan, regex=True)
df = df.replace('\t','',regex=True)
df = df.replace(' ','',regex=True)
df = df.replace('\?',np.nan,regex=True)
df = df.replace('\<',np.nan,regex=True)
df = df.replace('#NULL!',np.nan,regex=True)
#df = df.replace('99',np.nan,regex=True)
#df = df.replace(99,np.nan,regex=True)
#df

### Remove outliers

In [7]:
# Drop the column outliers as it is unrelated to the dependent variable
outliers = []
df = df.drop(outliers,axis=1)
df.head()

sex  m32  m33_1   PE  m33_2  m34  m35  m35_1_2  m35_2_2  m35_1_3  ...  \
0    1    1    1.0  1.0    1.0    1    2      1.0     11.0    999.0  ...   
1    1  999    NaN  NaN    NaN    5    1      NaN      NaN      NaN  ...   
2    1    2    1.0  1.0    1.0    1    1      NaN      NaN      NaN  ...   
3    1    5    2.0  2.0    3.0    2    1      NaN      NaN      NaN  ...   
4    1   60    2.0  2.0   45.0    5    1      NaN      NaN      NaN  ...   

   IPE5  IPE6  IPE7  IPE8  IPE9  IPE10  Age_Categ  Age_recode_2  IIEF5_Categ  \
0   NaN   5.0   5.0   NaN   0.0    0.0        NaN           NaN          NaN   
1   NaN   2.0   1.0   NaN   0.0    0.0        1.0           1.0          NaN   
2   NaN   5.0   5.0   NaN   0.0    0.0        NaN           NaN          NaN   
3   NaN   1.0   1.0   NaN   0.0    0.0        3.0           3.0          NaN   
4   4.0   3.0   5.0   5.0   4.0    3.0        1.0           1.0          2.0   

   IIEF_Y_N  
0       NaN  
1       NaN  
2       NaN  
3       NaN  
4       1.0  

[5 rows x 55 columns]

### Remove bad columns

In [8]:
def remove_bad_columns(df,bad_column_threshold):
    # find bad columns having too many missing values
    n_null = np.array(df.isnull().sum(axis=0))
    bad_col = np.array([]).astype(int)
    for i in range(len(n_null)):
        if n_null[i] >= bad_column_threshold:
            bad_col = np.append(bad_col,i)

    #print(bad_col)
    print('number of bad columns:',len(bad_col))

    # delete bad columns
    df = df.drop(df.columns[bad_col],axis=1)
    #df.info()
    return df  

In [9]:
df = remove_bad_columns(df,400)
df.info()

number of bad columns: 7
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1004 entries, 0 to 1003
Data columns (total 48 columns):
sex                    1004 non-null int64
m32                    1004 non-null int64
m33_1                  920 non-null float64
PE                     816 non-null float64
m33_2                  816 non-null float64
m34                    1004 non-null int64
m35                    1004 non-null int64
m42                    1004 non-null int64
m43                    1004 non-null int64
m44                    1004 non-null int64
m45                    1004 non-null int64
m46                    1004 non-null int64
m47                    1004 non-null int64
m48                    1004 non-null int64
m49                    1004 non-null int64
m50                    1004 non-null int64
m51                    1004 non-null int64
m52                    1004 non-null int64
m53                    1004 non-null int64
m54                    1004 non-null int64
m55  

### Remove bad rows

In [10]:
 # Find rows where target is missing
def find_missing_target_rows(df,target):
    # find rows where target is missing
    missing_row = df[target].isnull()
    print('Number of rows where target are missing:')
    print(sum(missing_row))

    #df = df[~missing_row]
    missing_row_indices = np.array([t for t in range(df.shape[0]) if missing_row[t]])
    
    return missing_row_indices

In [11]:
missing_target_rows = find_missing_target_rows(df,target)

Number of rows where target are missing:
238


We find bad rows which contain too many missing values, then remove them.

In [12]:
def find_bad_rows(df,bad_row_threshold):   
    # find bad rows having too many missing values
    n_null = np.array(df.isnull().sum(axis=1))
    bad_row = np.array([]).astype(int)
    for t in range(len(n_null)):
        if n_null[t] >= bad_row_threshold:
            bad_row = np.append(bad_row,t)

    #print(bad_row)
    print('number of bad rows:',len(bad_row))

    # delete bad rows
    #df = df.drop(bad_row)
    #df.info()
    return bad_row

In [13]:
bad_rows = find_bad_rows(df,5)
df.info()

number of bad rows: 339
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1004 entries, 0 to 1003
Data columns (total 48 columns):
sex                    1004 non-null int64
m32                    1004 non-null int64
m33_1                  920 non-null float64
PE                     816 non-null float64
m33_2                  816 non-null float64
m34                    1004 non-null int64
m35                    1004 non-null int64
m42                    1004 non-null int64
m43                    1004 non-null int64
m44                    1004 non-null int64
m45                    1004 non-null int64
m46                    1004 non-null int64
m47                    1004 non-null int64
m48                    1004 non-null int64
m49                    1004 non-null int64
m50                    1004 non-null int64
m51                    1004 non-null int64
m52                    1004 non-null int64
m53                    1004 non-null int64
m54                    1004 non-null int64
m55   

In [14]:
del_rows = np.union1d(missing_target_rows,bad_rows)
print('number of rows need to delete:',len(del_rows))

df = df.drop(del_rows)

number of rows need to delete: 339


### Separate target and attributes

In [15]:
dfx = df.drop(target,axis=1)
dfy = df[target]

### Find variable type

In [16]:
# number of uniques of each column (excluding NaN)
nu = np.array([len(pd.unique(dfx[col].dropna())) for col in dfx.columns])
print('number of uniques of each variable:')
print(nu)

number of uniques of each variable:
[ 1 29  3  2 25  7  3  5  6  5  6  5  5  6  6  6  6  5  5  5  5 60  6 18
  5  5  5  5  5 15  2 16 17  9  5  5  5  5  5  5  5  5  5  5  8  7  4]


In [17]:
def define_variable_type(df,nu):
    i_binary = [] ; i_category = [] ; i_continuous = []
    for i in range(len(nu)):
        if nu[i] == 2: # binary 
            i_binary.append(i)
        elif nu[i] < 5: # !!!! NOTE: this is not always correct, depending on data
            i_category.append(i)
        else:
            i_continuous.append(i)

    print('i_binary:',i_binary)
    print('i_category:',i_category)   
    #i_binary, i_category, i_continuous
    
    variable_type  = np.ones(len(nu))  # binary
    variable_type[i_category] = 2   # categorical
    variable_type[i_continuous] = 3 # continuous

    return variable_type #,i_binary,i_category,i_continuous

In [18]:
variable_type = define_variable_type(dfx,nu)
print('variable type:',variable_type)

i_binary: [3, 30]
i_category: [0, 2, 6, 46]
variable type: [2. 3. 2. 1. 3. 3. 2. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.
 3. 3. 3. 3. 3. 3. 1. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 2.]


### Impute missing values of attributes

In [19]:
def impute_missing(df,variable_type):
    # impute binary and categorical variables by the most frequency (in each column)
    # continuous variable by median
    # input: df: pandas data frame, variable_type: list
    # output: df2: pandas data frame
    df2 = df.copy()
    for i,col in enumerate(df.columns):
        if variable_type[i] < 3: # binary or caterogy
            df2[col] = df[col].fillna(df[col].mode().iloc[0])
        else: # continuous
            df2[col] = df[col].fillna(df[col].median())    
    return df2       

In [20]:
dfx_imputed = impute_missing(dfx,variable_type)
dfx_imputed.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 665 entries, 4 to 1002
Data columns (total 47 columns):
sex                    665 non-null int64
m32                    665 non-null int64
m33_1                  665 non-null float64
PE                     665 non-null float64
m33_2                  665 non-null float64
m34                    665 non-null int64
m35                    665 non-null int64
m42                    665 non-null int64
m43                    665 non-null int64
m44                    665 non-null int64
m45                    665 non-null int64
m46                    665 non-null int64
m47                    665 non-null int64
m48                    665 non-null int64
m49                    665 non-null int64
m50                    665 non-null int64
m51                    665 non-null int64
m52                    665 non-null int64
m53                    665 non-null int64
m54                    665 non-null int64
m55                    665 non-null int64
AGE   

## Data Processing

### Attributes

In [21]:
def convert_binary_and_category(x,variable_type):
    """
    convert binary to +-1, category to one hot; remain continuous.
    """    
    onehot_encoder = OneHotEncoder(sparse=False,categories='auto')

    # create 2 initial columns
    x_new = np.zeros((x.shape[0],2))

    for i,i_type in enumerate(variable_type):
        if i_type == 1: # binary
            unique_value = np.unique(x[:,i])
            x1 = np.array([-1. if value == unique_value[0] else 1. for value in x[:,i]])        
            x_new = np.hstack((x_new,x1[:,np.newaxis]))

        elif i_type == 2: # category
            x1 = onehot_encoder.fit_transform(x[:,i].reshape(-1,1))
            x_new = np.hstack((x_new,x1))
            
        else: # continuous      
            x_new = np.hstack((x_new,x[:,i][:,np.newaxis]))      

    # drop the 2 initial column
    x_new = x_new[:,2:]
    
    return x_new.astype(float)

In [22]:
# convert x
x = np.array(dfx_imputed)
x_new = convert_binary_and_category(x,variable_type)

print(x_new.shape)
print(x_new)

(665, 54)
[[ 1. 60.  0. ...  1.  0.  0.]
 [ 1.  5.  0. ...  1.  0.  0.]
 [ 1. 10.  0. ...  1.  0.  0.]
 ...
 [ 1. 45.  0. ...  1.  0.  0.]
 [ 1. 30.  0. ...  1.  0.  0.]
 [ 1. 10.  0. ...  1.  0.  0.]]


### Target

In [23]:
y = np.array(dfy)
#print(np.unique(y,return_counts=True))

# convert taget to 0 and 1
#y_new = y
y_new = np.ones(y.shape[0])
y_new[y == 2] = 0

print(np.unique(y_new,return_counts=True))

(array([0., 1.]), array([ 93, 572]))


In [24]:
# combine X and y and save to a file
xy_new = np.hstack((x_new,y_new[:,np.newaxis]))
np.savetxt('data_processed.dat',xy_new,fmt='%f')